'use strict';

// ── The two pending production changes, as constants ─────────────────────────
//
// These mirror supabase/migrations/20260830010000_understanding_records.sql
// and ops/db/proposed/fix-lesson-descriptions.sql, word for word where it
// matters. They live here as constants because the owner's machine turned out
// to have no psql, and the DATABASE_URL in Vercel is stored as a sensitive
// value that can never be read back — so the only thing that can reach the
// production database is the deployed backend itself. The admin maintenance
// route applies exactly these statements and nothing else: there is no
// arbitrary-SQL surface here.
//
// Both are idempotent. The table create is IF NOT EXISTS; the description
// updates set the same values however many times they run.

const CREATE_UNDERSTANDING_RECORDS = `
create table if not exists public.understanding_records (
  id            bigint generated by default as identity primary key,
  user_id       integer not null references public.users(user_id) on delete cascade,
  project_key   varchar(80) not null,
  project_title varchar(120) not null,
  skills        jsonb not null default '[]'::jsonb,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint uq_understanding_user_project unique (user_id, project_key)
);
create index if not exists idx_understanding_user on public.understanding_records(user_id);
alter table public.understanding_records enable row level security;
`;

// One row per learner per month the evidence email actually went out; the
// unique constraint is what makes the send button safe to press twice.
const CREATE_MONTHLY_DIGEST_LOG = `
create table if not exists public.monthly_digest_log (
  id       bigint generated by default as identity primary key,
  user_id  integer not null references public.users(user_id) on delete cascade,
  period   varchar(7) not null,
  status   varchar(20) not null default 'sent',
  sent_at  timestamptz not null default now(),
  constraint uq_digest_user_period unique (user_id, period)
);
alter table public.monthly_digest_log enable row level security;
`;

// Seven lesson descriptions carrying an older course's topics. The replacement
// text is the summary in src/pages/Lessons/lessonRegistry.js. Nothing invented.
const LESSON_DESCRIPTION_FIXES = [
  [3, 'Work with text using quotes, len(), and string methods'],
  [5, 'Repeat code automatically using for i in range()'],
  [6, 'Loop over characters and sequences with for loops'],
  [7, 'Create and use Python lists. Index, append, and len()'],
  [8, 'Combine loops and lists to process collections of data'],
  [9, 'Write reusable functions using def, parameters, and return'],
  [10, 'Put it all together. Functions, loops, and lists in one program'],
];

module.exports = { CREATE_MONTHLY_DIGEST_LOG, CREATE_UNDERSTANDING_RECORDS, LESSON_DESCRIPTION_FIXES };
