const lesson26 = {
  id: 26,
  title: "Scope — Where a Variable Lives",
  subtitle: "Why the thing you made inside a function vanishes outside it.",
  emoji: "🏠",
  xp: 50,
  story: "You wrote a variable inside a function, tried to use it outside, and Python said it does not exist. It is not a bug — it is a rule, and it exists to protect you.",
  steps: [
    {
      type: 'concept',
      id: 'concept',
      title: 'Inside Stays Inside',
      body: 'A variable made inside a function only exists while that function is running. When it finishes, the variable is gone. Variables made outside can be read from inside — but to change one, you have to say so with global, which you almost never should.',
      highlight: 'score = 0            # global — everyone can read it\n\ndef play():\n    bonus = 10       # local — only exists in here\n    print(score)     # fine, reading is allowed\n\nplay()\nprint(bonus)         # error: bonus is gone',
      code: 'score = 0\n\ndef play():\n    bonus = 10\n    print("Inside, bonus is", bonus)\n    print("Inside, score is", score)\n\nplay()\nprint("Outside, score is", score)',
    },
    {
      type: 'predict',
      id: 'predict-scope',
      title: 'Did It Change?',
      question: 'What does this print?',
      code: 'score = 5\n\ndef add_points():\n    score = 100\n\nadd_points()\nprint(score)',
      choices: ['100', '5', 'None', 'An error'],
      correct: 1,
      explain: 'Correct. The score inside the function is a different, local variable. The outer one was never touched.',
      wrongHint: 'Assigning inside a function makes a brand new local variable, even if the name matches one outside.',
      hints: [
        'There are two variables here that happen to share a name.',
        'The local one disappears the moment the function ends.',
      ],
    },
    {
      type: 'predict',
      id: 'predict-read',
      title: 'Reading Is Different',
      question: 'And this one?',
      code: 'lives = 3\n\ndef show():\n    print("Lives:", lives)\n\nshow()',
      choices: ['Lives: 3', 'An error, lives is not defined', 'Lives: None', 'Nothing at all'],
      correct: 0,
      explain: 'Yes. Reading an outer variable from inside a function is allowed. Only assigning creates a new local one.',
      wrongHint: 'This function reads lives, it does not assign to it.',
      hints: ['Look for an = sign inside the function. There is not one.', 'Reading out, yes. Writing in, no.'],
    },
    {
      type: 'example',
      id: 'example',
      title: 'The Right Way to Change It',
      description: 'Instead of reaching outside, take a value in and hand a new one back. Run it.',
      code: 'def add_points(current, points):\n    return current + points\n\nscore = 5\nscore = add_points(score, 20)\nprint("Score is now", score)',
      expectedOutput: /Score is now 25/,
    },
    {
      type: 'tryit',
      id: 'tryit',
      title: 'Keep the Function Honest',
      description: 'This function takes what it needs and returns what it made. Nothing outside it can be surprised.',
      code: 'def level_up(level, xp):\n    new_level = level + 1\n    new_xp = xp + 100\n    return new_level, new_xp\n\nlevel, xp = 2, 350\nlevel, xp = level_up(level, xp)\nprint("Level", level, "with", xp, "XP")',
      expectedOutput: /Level 3 with 450 XP/,
      expectedKeywords: ['return'],
      wrongOutputHint: 'You should end on level 3 with 450 XP.',
      hints: [
        'new_level and new_xp only exist inside the function — that is fine, they get returned.',
        'The two variables outside are updated by the assignment, not by the function reaching out.',
      ],
    },
    {
      type: 'challenge',
      id: 'challenge',
      title: 'What global Really Does',
      description: 'global lets a function change an outer variable. Run it, then think about why this is usually a bad idea.',
      optional: true,
      code: 'coins = 0\n\ndef collect():\n    global coins\n    coins = coins + 1\n\ncollect()\ncollect()\nprint("Coins:", coins)',
      expectedOutput: /Coins: 2/,
      expectedKeywords: ['global'],
      wrongOutputHint: 'Two calls to collect should leave you with 2 coins.',
      hints: [
        'Without the global line, coins outside would stay at 0.',
        'The reason to avoid it: now any function anywhere can change coins, and finding out which one did is hard.',
      ],
    },
  ],
};

export default lesson26;
