const lesson29 = {
  id: 29,
  title: "Classes and Objects. Your Own Kind of Thing",
  subtitle: "Build a blueprint once, then stamp out as many as you like.",
  emoji: "🏗️",
  xp: 50,
  story: "Your game has twenty enemies. Twenty dictionaries with the same keys is a chore. One class is a blueprint. And every enemy made from it already knows how to attack.",
  steps: [
    {
      type: 'concept',
      id: 'concept',
      title: 'A Blueprint and Its Copies',
      body: 'class defines the blueprint. __init__ runs whenever a new one is made, and self is that particular one. This enemy, not enemies in general. Functions inside a class are called methods, and they always take self first.',
      highlight: 'class Enemy:\n    def __init__(self, name, health):\n        self.name = name       # store it on THIS enemy\n        self.health = health\n\n    def hit(self, damage):\n        self.health = self.health - damage\n\ngoblin = Enemy("Goblin", 30)   # __init__ runs here\ngoblin.hit(10)                 # self is goblin',
      code: 'class Enemy:\n    def __init__(self, name, health):\n        self.name = name\n        self.health = health\n\n    def hit(self, damage):\n        self.health = self.health - damage\n        print(self.name, "now has", self.health, "health")\n\ngoblin = Enemy("Goblin", 30)\ngoblin.hit(10)',
    },
    {
      type: 'predict',
      id: 'predict-self',
      title: 'Two Copies, Two Lives',
      question: 'What does this print?',
      code: 'class Pet:\n    def __init__(self, name):\n        self.name = name\n\na = Pet("Rex")\nb = Pet("Milo")\nprint(a.name)',
      choices: ['Rex', 'Milo', 'Rex Milo', 'An error'],
      correct: 0,
      explain: 'Correct. A and b are separate objects. Making b did not touch a.',
      wrongHint: 'Each object made from a class keeps its own values. They do not share.',
      hints: ['Two Pet(...) calls means two separate pets.', 'a.name was set when a was made.'],
    },
    {
      type: 'fillblank',
      id: 'fill-class',
      title: 'Write the Blueprint',
      question: 'Finish this class so every hero starts with a name and 100 health.',
      template: '___ Hero:\n    def __init__(___, name):\n        self.name = name\n        ___.health = 100\n\nnova = Hero("Nova")\nprint(nova.health)',
      options: ['class', 'def', 'self', 'this'],
      answers: ['class', 'self', 'self'],
      explain: 'Yes. Class starts the blueprint, and self is how each object refers to itself. Python uses self, not this.',
      wrongHint: 'One word starts a blueprint. The other is the name Python gives to "this particular one".',
      hints: [
        'The first line defines a new kind of thing.',
        '__init__ always takes self as its very first parameter.',
      ],
    },
    {
      type: 'example',
      id: 'example',
      title: 'A Whole Battle',
      description: 'Two objects from one class, fighting. Run it.',
      code: 'class Fighter:\n    def __init__(self, name, health, power):\n        self.name = name\n        self.health = health\n        self.power = power\n\n    def attack(self, other):\n        other.health = other.health - self.power\n        print(self.name, "hits", other.name, "for", self.power)\n\n    def is_alive(self):\n        return self.health > 0\n\nhero = Fighter("Nova", 40, 12)\ngoblin = Fighter("Goblin", 30, 8)\n\nwhile hero.is_alive() and goblin.is_alive():\n    hero.attack(goblin)\n    if goblin.is_alive():\n        goblin.attack(hero)\n\nwinner = hero.name if hero.is_alive() else goblin.name\nprint("Winner:", winner)',
      expectedOutput: /Winner:/,
    },
    {
      type: 'tryit',
      id: 'tryit',
      title: 'Build Your Own Class',
      description: 'A Dog with a name and a trick. Change the name, change the trick, add a second dog.',
      code: 'class Dog:\n    def __init__(self, name, trick):\n        self.name = name\n        self.trick = trick\n\n    def show_off(self):\n        print(self.name, "can", self.trick + "!")\n\nrex = Dog("Rex", "roll over")\nmilo = Dog("Milo", "play dead")\nrex.show_off()\nmilo.show_off()',
      expectedOutput: /can/,
      expectedKeywords: ['class', 'self'],
      wrongOutputHint: 'Both dogs should show off their own trick.',
      hints: [
        'Every method inside a class takes self as its first parameter.',
        'Make a third dog and call show_off on it too.',
      ],
    },
    {
      type: 'challenge',
      id: 'challenge',
      title: 'A Counter That Remembers',
      description: 'An object can hold state between calls. Watch the count climb.',
      optional: true,
      code: 'class Counter:\n    def __init__(self):\n        self.count = 0\n\n    def click(self):\n        self.count = self.count + 1\n        return self.count\n\nc = Counter()\nc.click()\nc.click()\nprint("Clicked", c.click(), "times")',
      expectedOutput: /Clicked 3 times/,
      expectedKeywords: ['class', 'self'],
      wrongOutputHint: 'Three clicks should report 3.',
      hints: [
        'self.count survives between calls because it lives on the object.',
        'A plain variable inside click would reset to 0 every time.',
      ],
    },
  ],
};

export default lesson29;
