const lesson2 = {
  id: 2,
  title: "Storing Info with Variables",
  subtitle: "Save names, numbers, and messages in Python — like labeling boxes!",
  emoji: "📦",
  story: "A game needs to remember your name and your score. A variable is the box it keeps them in.",
  steps: [
    {
      type: 'concept',
      id: 'concept',
      title: 'What is a Variable?',
      body: 'A variable is like a labeled box. You store a value inside and give the box a name. Later, Python opens the box and uses what is inside!',
      highlight: 'name = "Alex"   stores the text:   Alex\nage  = 10       stores the number: 10',
      code: 'name = "Alex"\nage = 10\nprint(name)\nprint(age)',
    },
    {
      type: 'predict',
      id: 'predict-variable',
      title: 'What Is In The Box Now?',
      question: 'What does this print?',
      code: 'score = 10\nscore = 25\nprint(score)',
      choices: ['10', '25', '10 25', '35'],
      correct: 1,
      explain: 'Correct. A variable holds one thing at a time — the second line replaced the first.',
      wrongHint: 'Assigning again does not add to a variable, it replaces what was inside.',
      hints: ['Read the lines top to bottom.', 'The box can only hold one value. What was the last thing put in it?'],
    },
    {
      type: 'example',
      id: 'example',
      title: 'Variables in Action',
      description: 'Click Run to see how Python stores a name in a variable and prints it!',
      code: 'name = "Alex"\nprint(name)',
      successPattern: /Alex/,
      hint: 'Click Run! The variable name holds "Alex" and print(name) shows it on screen.',
      xp: 10,
    },
    {
      type: 'tryit',
      id: 'tryit',
      title: 'Store Your Own Info',
      description: 'Change "Alex" to YOUR name and 10 to YOUR age. Click Run to see your own info printed!',
      code: 'name = "Alex"\nage = 10\nprint(name)\nprint(age)',
      expectedKeywords: ['name', 'age', 'print('],
      wrongOutputHint: 'Keep both variables — name and age — and print each one.',
      hint: 'Change "Alex" to your name and 10 to your age, then click Run!',
      xp: 15,
    },
    {
      type: 'challenge',
      id: 'challenge',
      title: 'Your Character Sheet',
      description: 'Change all three variables — name, age, and superpower — to your own. Click Run to show your character sheet!',
      code: 'name = "Alex"\nage = 10\nsuperpower = "flying"\nprint(name)\nprint(age)\nprint(superpower)',
      expectedKeywords: ['name', 'age', 'superpower'],
      wrongOutputHint: 'All three variables need to still be there: name, age and superpower.',
      hint: 'Change "Alex", 10, and "flying" to your own name, age, and favorite superpower!',
      xp: 20,
    },
  ]
};

export default lesson2;
