const lesson25 = {
  id: 25,
  title: "Functions That Give Things Back",
  subtitle: "Default answers, more than one result, and the meaning of None.",
  emoji: "🎁",
  xp: 50,
  story: "You wrote functions back in Lesson 9. Now make them properly useful: with sensible defaults, and answers you can actually use somewhere else.",
  steps: [
    {
      type: 'concept',
      id: 'concept',
      title: 'Print Is Not Return',
      body: 'A function that prints shows you something and then forgets it. A function that returns hands the value back so you can store it, add to it, or pass it on. A function with no return gives back None — Python’s word for "nothing here".',
      highlight: 'def double(n):\n    return n * 2      # hands it back\n\ndef show(n):\n    print(n * 2)      # shows it, gives back None\n\nresult = double(5)    # 10\nnothing = show(5)     # prints 10, result is None',
      code: 'def double(n):\n    return n * 2\n\ndef show(n):\n    print(n * 2)\n\nprint(double(5) + 1)\nprint(show(5))',
    },
    {
      type: 'predict',
      id: 'predict-none',
      title: 'What Does It Give Back?',
      question: 'What does this print?',
      code: 'def greet(name):\n    print("Hi", name)\n\nanswer = greet("Ada")\nprint(answer)',
      choices: ['Hi Ada\nHi Ada', 'Hi Ada\nNone', 'Hi Ada', 'An error'],
      correct: 1,
      explain: 'Correct. greet prints, but returns nothing — so answer is None, and printing it shows None.',
      wrongHint: 'The function has no return line. What does Python hand back when there is nothing to hand back?',
      hints: ['There are two prints in this program, so two lines of output.', 'A function with no return gives back None.'],
    },
    {
      type: 'concept',
      id: 'concept-default',
      title: 'A Sensible Default',
      body: 'Give a parameter a default value and the caller can leave it out. It makes a function easy to use for the common case and still flexible when you need it.',
      highlight: 'def greet(name, greeting="Hello"):\n    return greeting + ", " + name\n\ngreet("Ada")           # "Hello, Ada"\ngreet("Ada", "Hiya")   # "Hiya, Ada"',
      code: 'def greet(name, greeting="Hello"):\n    return greeting + ", " + name\n\nprint(greet("Ada"))\nprint(greet("Sam", "Hiya"))',
    },
    {
      type: 'fillblank',
      id: 'fill-default',
      title: 'Give It a Default',
      question: 'Make the power default to 2, so square is what happens if nobody says otherwise.',
      template: 'def raise_to(number, power___2):\n    ___ number ** power\n\nprint(raise_to(5))',
      options: ['=', '==', 'return', 'print'],
      answers: ['=', 'return'],
      explain: 'Yes. A single = sets the default, and return is what makes the answer usable.',
      wrongHint: 'One = sets a value. Two == asks a question. And the answer has to come back out somehow.',
      hints: ['A default is an assignment, not a comparison.', 'print shows; return gives back.'],
    },
    {
      type: 'example',
      id: 'example',
      title: 'Two Answers at Once',
      description: 'Return several values separated by commas, and unpack them on the other side.',
      code: 'def stats(numbers):\n    return min(numbers), max(numbers), sum(numbers)\n\nlowest, highest, total = stats([4, 9, 2, 7])\nprint("Lowest:", lowest)\nprint("Highest:", highest)\nprint("Total:", total)',
      expectedOutput: /Total: 22/,
    },
    {
      type: 'tryit',
      id: 'tryit',
      title: 'A Damage Calculator',
      description: 'Write a function that works out damage, with a default multiplier of 1. Try calling it both ways.',
      code: 'def damage(base, multiplier=1):\n    return base * multiplier\n\nprint("Normal hit:", damage(10))\nprint("Critical hit:", damage(10, 3))',
      expectedOutput: /Critical hit: 30/,
      expectedKeywords: ['def', 'return'],
      wrongOutputHint: 'A normal hit should be 10 and a critical hit 30.',
      hints: [
        'The default goes in the def line, after the parameter name.',
        'Calling it with one argument uses the default; two overrides it.',
      ],
    },
    {
      type: 'challenge',
      id: 'challenge',
      title: 'Early Return',
      description: 'A function stops the moment it hits a return. Use that to answer a question and get out.',
      optional: true,
      code: 'def find_first_big(numbers):\n    for n in numbers:\n        if n > 100:\n            return n\n    return None\n\nprint(find_first_big([5, 40, 220, 300]))\nprint(find_first_big([1, 2, 3]))',
      expectedOutput: /220[\s\S]*None/,
      expectedKeywords: ['return'],
      wrongOutputHint: 'The first call should give 220 and the second None.',
      hints: [
        'The return inside the loop ends the whole function, not just the lap.',
        'The final return None is what happens when nothing was found.',
      ],
    },
  ],
};

export default lesson25;
