const lesson28 = {
  id: 28,
  title: "Enumerate and Zip",
  subtitle: "Count while you loop, and walk two lists side by side.",
  emoji: "🔗",
  xp: 50,
  story: "A leaderboard needs positions: 1st, 2nd, 3rd. And a quiz needs each question matched with its answer. Two tools, both one word long.",
  steps: [
    {
      type: 'concept',
      id: 'concept',
      title: 'The Counter You Do Not Have to Keep',
      body: 'enumerate gives you the position and the item together, so you stop writing counter = counter + 1 by hand. zip walks two lists at the same time, handing you one item from each.',
      highlight: 'for position, name in enumerate(names):\n    ...\n\nfor position, name in enumerate(names, start=1):\n    ...   # 1st, 2nd, 3rd instead of 0, 1, 2\n\nfor question, answer in zip(questions, answers):\n    ...',
      code: 'names = ["Nova", "Blaze", "Echo"]\nfor position, name in enumerate(names, start=1):\n    print(position, name)',
    },
    {
      type: 'predict',
      id: 'predict-enumerate',
      title: 'Where Does Counting Start?',
      question: 'What does this print?',
      code: 'fruits = ["apple", "pear"]\nfor i, fruit in enumerate(fruits):\n    print(i, fruit)',
      choices: ['1 apple\n2 pear', '0 apple\n1 pear', 'apple 0\npear 1', '0\n1'],
      correct: 1,
      explain: 'Right — without start=1, enumerate counts from 0 like everything else in Python.',
      wrongHint: 'The position comes first, and Python counts from zero unless you tell it not to.',
      hints: ['enumerate hands back the position first, then the item.', 'There is no start= here.'],
    },
    {
      type: 'fillblank',
      id: 'fill-zip',
      title: 'Pair Them Up',
      question: 'Match each player with their score.',
      template: 'players = ["Nova", "Blaze"]\nscores = [40, 65]\nfor name, points in ___(players, scores):\n    print(name, "scored", points)',
      options: ['zip', 'enumerate', 'range', 'len'],
      answers: ['zip'],
      explain: 'Exactly. zip pairs the first with the first, the second with the second, and stops when the shorter list runs out.',
      wrongHint: 'You are walking two lists together, not counting positions in one.',
      hints: ['enumerate is for positions. This needs two lists.', 'Think of a zip on a coat: two sides, joined tooth by tooth.'],
    },
    {
      type: 'example',
      id: 'example',
      title: 'A Real Leaderboard',
      description: 'Run it. enumerate does the ranking for you.',
      code: 'scores = {"Blaze": 65, "Nova": 40, "Echo": 22}\nranked = sorted(scores.items(), key=lambda pair: pair[1], reverse=True)\n\nfor place, (name, points) in enumerate(ranked, start=1):\n    print(place, name, points)',
      expectedOutput: /1 Blaze 65/,
    },
    {
      type: 'tryit',
      id: 'tryit',
      title: 'Mark the Quiz',
      description: 'Compare each given answer with the correct one and count how many match.',
      code: 'correct = ["a", "c", "b", "d"]\ngiven = ["a", "b", "b", "d"]\n\nright = 0\nfor mine, theirs in zip(given, correct):\n    if mine == theirs:\n        right = right + 1\n\nprint("Score:", right, "out of", len(correct))',
      expectedOutput: /Score: 3 out of 4/,
      expectedKeywords: ['zip'],
      wrongOutputHint: 'Three of the four answers match, so the score should read 3 out of 4.',
      hints: [
        'zip gives you one answer from each list per lap.',
        'Change one of the given answers and the score should change too.',
      ],
    },
    {
      type: 'challenge',
      id: 'challenge',
      title: 'Number Every Line',
      description: 'Print a numbered shopping list, with the numbers starting at 1.',
      optional: true,
      code: 'shopping = ["bread", "apples", "cheese"]\nfor number, item in enumerate(shopping, start=1):\n    print(str(number) + ". " + item)',
      expectedOutput: /1\. bread/,
      expectedKeywords: ['enumerate'],
      wrongOutputHint: 'The first line should read "1. bread".',
      hints: [
        'start=1 makes the counting begin at one instead of zero.',
        'str(number) turns the number into text so it can join the item with +.',
      ],
    },
  ],
};

export default lesson28;
