const lesson7 = {
  id: 7,
  title: "Basic Lists",
  subtitle: "Store many values in one place — then grab any one you need!",
  emoji: "📋",
  story: "One variable holds one thing. A list holds a whole team, a whole inventory, a whole scoreboard.",
  steps: [
    {
      type: 'concept',
      id: 'concept',
      title: 'Lists Hold Many Values',
      body: 'A list stores many items inside square brackets, separated by commas. Each item has an index — the first item is index 0. You can add new items to a list with .append()!',
      highlight: 'fruits = ["apple", "banana", "mango"]\nprint(fruits[0])   →   apple\nprint(fruits[1])   →   banana',
      code: 'fruits = ["apple", "banana", "mango"]\nprint(fruits[0])\nprint(fruits[1])\nprint(fruits[2])',
    },
    {
      type: 'predict',
      id: 'predict-index',
      title: 'Which One Is Number 1?',
      question: 'What does this print?',
      code: 'pets = ["cat", "dog", "fish"]\nprint(pets[1])\nprint(len(pets))',
      choices: ['cat\n3', 'dog\n3', 'dog\n2', 'cat\n2'],
      correct: 1,
      explain: 'Correct. Position 1 is the second item, because counting starts at 0. And there are three pets.',
      wrongHint: 'Lists start counting at 0, so position 1 is not the first item.',
      hints: ['pets[0] is "cat". So what is pets[1]?', 'len() counts the items, and counting items does start at 1.'],
    },
    {
      type: 'example',
      id: 'example',
      title: 'Access by Index',
      description: 'Click Run to create a list and pick out specific items by their index!',
      code: 'colors = ["red", "green", "blue"]\nprint(colors[0])\nprint(colors[2])',
      successPattern: /red|blue/i,
      hint: 'Click Run! colors[0] gets the first item, colors[2] gets the third item.',
      xp: 10,
    },
    {
      type: 'tryit',
      id: 'tryit',
      title: 'Add to a List',
      description: 'Run this code to see .append() add a new item. Then add another item of your own!',
      code: 'animals = ["cat", "dog"]\nanimals.append("rabbit")\nprint(animals)',
      successPattern: /rabbit/i,
      hint: '.append() adds a new item to the end of the list. Add another animal after "rabbit"!',
      xp: 15,
    },
    {
      type: 'challenge',
      id: 'challenge',
      title: 'List Length',
      description: 'Run this code to count how many items are in a list. Then add more and run again!',
      code: 'snacks = ["apple", "chips", "yogurt"]\nprint("Snacks:", snacks)\nprint("Count:", len(snacks))',
      successPattern: /Count:/i,
      hint: 'len() counts the items in the list. Append a new snack and run again to see the count go up!',
      xp: 20,
    },
  ]
};

export default lesson7;
