const lesson18 = {
  id: 18,
  title: "Break and Continue. Stop or Skip",
  subtitle: "Two words that let you take control of a loop mid-lap.",
  emoji: "🛑",
  xp: 50,
  story: "You are searching a list of treasure chests. Once you find the gold, why keep opening chests? break gets you out.",
  steps: [
    {
      type: 'concept',
      id: 'concept',
      title: 'Two Escape Hatches',
      body: 'break leaves the loop straight away. No more laps at all. Continue skips the rest of this lap only, and jumps to the next one. Everything after them in the loop body is not run.',
      highlight: 'for chest in chests:\n    if chest == "gold":\n        break      # leave the whole loop\n    if chest == "empty":\n        continue   # skip to the next chest',
      code: 'chests = ["empty", "rock", "gold", "rock"]\nfor chest in chests:\n    if chest == "gold":\n        print("Found the gold!")\n        break\n    print("Opened a", chest)',
    },
    {
      type: 'predict',
      id: 'predict-break',
      title: 'Where Does It Stop?',
      question: 'What does this print?',
      code: 'for n in [1, 2, 3, 4, 5]:\n    if n == 3:\n        break\n    print(n)',
      choices: ['1\n2', '1\n2\n3', '1\n2\n4\n5', '1\n2\n3\n4\n5'],
      correct: 0,
      explain: 'Correct. When n is 3 the loop breaks before the print, so 3 never appears and 4 and 5 never happen.',
      wrongHint: 'break happens before the print on that lap, and there are no laps after it.',
      hints: [
        'Read the loop body in order: the if comes first, the print comes second.',
        'break does not just skip this lap. It ends the loop completely.',
      ],
    },
    {
      type: 'predict',
      id: 'predict-continue',
      title: 'And With Continue?',
      question: 'Same loop, but with continue instead. What prints now?',
      code: 'for n in [1, 2, 3, 4, 5]:\n    if n == 3:\n        continue\n    print(n)',
      choices: ['1\n2', '1\n2\n4\n5', '1\n2\n3\n4\n5', '3'],
      correct: 1,
      explain: 'Yes. Continue skips only the lap where n is 3. The loop carries on with 4 and 5.',
      wrongHint: 'continue skips one lap. It does not end the loop.',
      hints: ['Which single number does the if catch?', 'Every other number reaches the print as usual.'],
    },
    {
      type: 'example',
      id: 'example',
      title: 'Skip the Empties',
      description: 'Run it. Continue quietly passes over the empty chests.',
      code: 'chests = ["empty", "silver", "empty", "gold"]\nfor chest in chests:\n    if chest == "empty":\n        continue\n    print("You found", chest)',
      expectedOutput: /gold/,
    },
    {
      type: 'tryit',
      id: 'tryit',
      title: 'Stop at the First Big Number',
      description: 'Print each score until you hit one over 100, then stop the loop.',
      code: 'scores = [10, 55, 8, 130, 42]\nfor score in scores:\n    if score > 100:\n        print("Too big! Stopping.")\n        break\n    print("Score:", score)',
      expectedOutput: /Too big!/,
      expectedKeywords: ['break'],
      wrongOutputHint: 'The loop should announce that it stopped. Check the message inside the if.',
      hints: [
        'The if goes before the print, so a big score never gets printed.',
        'Try changing 130 to 90. now nothing stops the loop and every score prints.',
      ],
    },
    {
      type: 'challenge',
      id: 'challenge',
      title: 'Odd Numbers Only',
      description: 'Use continue to skip every even number between 1 and 10.',
      optional: true,
      code: 'for n in range(1, 11):\n    if n % 2 == 0:\n        continue\n    print(n)',
      expectedOutput: /^1\n3\n5\n7\n9$/m,
      expectedKeywords: ['continue'],
      wrongOutputHint: 'You want 1, 3, 5, 7 and 9 only. Check what the if is catching.',
      hints: [
        'n % 2 is the remainder after dividing by 2. Even numbers leave 0.',
        'continue on the even ones means only odd ones reach the print.',
      ],
    },
  ],
};

export default lesson18;
