const lesson4 = {
  id: 4,
  title: "Making Decisions with If Statements",
  subtitle: "Teach Python to choose different paths — like a Choose-Your-Own-Adventure story!",
  emoji: "🔀",
  story: "A game with no choices is a film. if is where your program starts making decisions.",
  steps: [
    {
      type: 'concept',
      id: 'concept',
      title: 'How Python Makes Decisions',
      body: 'If statements let your code choose what to do based on a condition. Is the age over 13? Take one path. Is it not? Take another. Python checks the condition and picks the right path!',
      highlight: 'if age >= 13:\n    print("Teen!")   # runs when TRUE\nelse:\n    print("Kid!")    # runs when FALSE',
      code: 'age = 15\nif age >= 13:\n    print("Teen!")\nelse:\n    print("Kid!")',
    },
    {
      type: 'predict',
      id: 'predict-branch',
      title: 'Which Path Does It Take?',
      question: 'What does this print?',
      code: 'age = 10\nif age >= 13:\n    print("Teen")\nelif age >= 8:\n    print("Kid")\nelse:\n    print("Little")',
      choices: ['Teen', 'Kid', 'Little', 'Kid\nLittle'],
      correct: 1,
      explain: 'Correct. 10 is not 13 or more, but it is 8 or more, so the elif wins — and once one branch runs, the rest are skipped.',
      wrongHint: 'Check each condition in order from the top. The first one that is True is the only one that runs.',
      hints: ['Is 10 greater than or equal to 13?', 'Only one branch of an if/elif/else ever runs.'],
    },
    {
      type: 'example',
      id: 'example',
      title: 'If and Else',
      description: 'Click Run to see if/else in action. Then try changing age = 15 to age = 8 and click Run again!',
      code: 'age = 15\nif age >= 13:\n    print("Teen!")\nelse:\n    print("Kid!")',
      successPattern: /Teen|Kid/,
      hint: 'Click Run first. Then change 15 to 8 and run again — Python picks the other message!',
      xp: 10,
    },
    {
      type: 'tryit',
      id: 'tryit',
      title: 'Three Choices with elif',
      description: 'Run this code. Then try changing temp to 30, then to 5. Does Python pick the right message each time?',
      code: 'temp = 20\nif temp > 25:\n    print("Hot day!")\nelif temp > 15:\n    print("Nice day!")\nelse:\n    print("Cold day!")',
      successPattern: /day!/,
      hint: 'Try temp = 30 for Hot day, temp = 20 for Nice day, temp = 5 for Cold day.',
      xp: 15,
    },
    {
      type: 'challenge',
      id: 'challenge',
      title: 'Secret Password Checker',
      description: 'Run the code. Then change the password to something wrong — what happens? Change it back to see it work!',
      code: 'password = "python123"\nif password == "python123":\n    print("Access granted!")\nelse:\n    print("Wrong password!")',
      successPattern: /Access|Wrong/,
      hint: 'Change "python123" to any other word and see the else branch run!',
      xp: 20,
    },
  ]
};

export default lesson4;
