const lesson22 = {
  id: 22,
  title: "Tuples and Sets",
  subtitle: "One list that cannot change, and one that refuses repeats.",
  emoji: "🔒",
  xp: 50,
  story: "Some things should never be edited by accident. The size of your game screen, for instance. And some things should never appear twice, like the list of players who have joined.",
  steps: [
    {
      type: 'concept',
      id: 'concept',
      title: 'Locked and Unique',
      body: 'A tuple looks like a list but uses round brackets, and once it is made it cannot be changed. A set uses curly braces and silently throws away any duplicates. Both are ordinary Python, and both save you from a whole class of bug.',
      highlight: 'screen = (800, 600)      # a tuple. Locked\nplayers = {"Sam", "Ada"}  # a set. No repeats\n\nplayers.add("Sam")        # already there, nothing happens',
      code: 'screen = (800, 600)\nprint("Width:", screen[0])\n\nplayers = {"Sam", "Ada", "Sam"}\nprint("Players:", len(players))',
    },
    {
      type: 'predict',
      id: 'predict-set',
      title: 'How Many Are There?',
      question: 'What number does this print?',
      code: 'colours = {"red", "blue", "red", "green", "blue"}\nprint(len(colours))',
      choices: ['5', '3', '2', 'An error'],
      correct: 1,
      explain: 'Yes. A set keeps only one of each. Red, blue and green, so three.',
      wrongHint: 'Count how many different colours there are, not how many are written down.',
      hints: ['A set throws duplicates away as it is built.', 'How many unique words are in those five?'],
    },
    {
      type: 'predict',
      id: 'predict-tuple',
      title: 'Try to Change It',
      question: 'What happens when this runs?',
      code: 'screen = (800, 600)\nscreen[0] = 1024\nprint(screen)',
      // This sample is meant to crash — that is the answer.
      expectsError: true,
      choices: [
        'It prints (1024, 600)',
        'It prints (800, 600)',
        'It crashes with an error',
        'It prints 1024',
      ],
      correct: 2,
      explain: 'Right. That is the whole point of a tuple. Python refuses, loudly, rather than letting it change quietly.',
      wrongHint: 'A tuple cannot be changed after it is made. What does Python do when you try anyway?',
      hints: ['Round brackets mean locked.', 'Python does not fail silently. It tells you.'],
    },
    {
      type: 'example',
      id: 'example',
      title: 'Unpacking a Tuple',
      description: 'Run it. Two variables get filled from one tuple in a single line.',
      code: 'screen = (800, 600)\nwidth, height = screen\nprint("Width is", width)\nprint("Height is", height)',
      expectedOutput: /Height is 600/,
    },
    {
      type: 'tryit',
      id: 'tryit',
      title: 'Remove the Repeats',
      description: 'A list of visitors with duplicates. Turn it into a set to find out how many different people came.',
      code: 'visitors = ["Sam", "Ada", "Sam", "Jo", "Ada", "Sam"]\nunique = set(visitors)\nprint("Visits:", len(visitors))\nprint("Different people:", len(unique))',
      expectedOutput: /Different people: 3/,
      expectedKeywords: ['set'],
      wrongOutputHint: 'Six visits, three different people. Check that you wrapped the list in set().',
      hints: [
        'set(a_list) builds a set from a list, dropping the repeats.',
        'Add another "Jo" to the list. The visit count grows but the people count does not.',
      ],
    },
    {
      type: 'challenge',
      id: 'challenge',
      title: 'Who Played Both Games?',
      description: 'Two sets of players. Find the ones who appear in both.',
      optional: true,
      code: 'chess = {"Sam", "Ada", "Jo"}\nmaths = {"Ada", "Jo", "Nia"}\nboth = chess & maths\nprint("Played both:", both)\nprint("Played either:", chess | maths)',
      expectedOutput: /Played both/,
      expectedKeywords: ['&'],
      wrongOutputHint: 'The first line should show only the names in both sets: Ada and Jo.',
      hints: [
        '& means "in both". | means "in either one".',
        'Add a name to one set and watch which line changes.',
      ],
    },
  ],
};

export default lesson22;
