const lesson31 = {
  id: 31,
  title: "Capstone — Build a Real Game",
  subtitle: "Everything you have learned, in one program you can keep.",
  emoji: "🏆",
  xp: 100,
  story: "This is the last lesson. There is nothing new in it — every piece is something you already know. Putting them together is what makes you a programmer.",
  steps: [
    {
      type: 'concept',
      id: 'concept',
      title: 'How a Real Program Is Built',
      body: 'Nobody writes a whole game in one go. You build one small piece, run it, check it works, and only then add the next. Every game in this lesson grows the same way: data first, then one function, then the loop that ties them together.',
      highlight: '# 1. the data       — dictionaries and lists\n# 2. the functions  — one job each\n# 3. the loop       — while the game is still going\n# 4. the ending     — print the result',
      code: 'rooms = {\n    "hall": "A dusty hall with two doors.",\n    "library": "Books everywhere. One looks new.",\n}\n\ndef describe(room):\n    return rooms.get(room, "Nothing here.")\n\nprint(describe("hall"))\nprint(describe("cellar"))',
    },
    {
      type: 'order',
      id: 'order-structure',
      title: 'What Order Do You Build In?',
      question: 'Put these stages of building a game into a sensible order.',
      shuffled: [
        'Add the loop that keeps the game going',
        'Decide what data the game needs',
        'Print the ending when the loop stops',
        'Write one function and test it on its own',
      ],
      correctOrder: [
        'Decide what data the game needs',
        'Write one function and test it on its own',
        'Add the loop that keeps the game going',
        'Print the ending when the loop stops',
      ],
      explain: 'That is how real programs get built — smallest working piece first, then the next one.',
      wrongHint: 'You cannot write a function until you know what data it works on, and you cannot loop until the function works.',
    },
    {
      type: 'example',
      id: 'example',
      title: 'A Complete Treasure Hunt',
      description: 'Read it before you run it. Every single line uses something from an earlier lesson.',
      code: 'import random\n\nclass Player:\n    def __init__(self, name):\n        self.name = name\n        self.coins = 0\n        self.energy = 5\n\n    def is_playing(self):\n        return self.energy > 0\n\nchests = ["gold", "empty", "gems", "empty", "trap"]\nprizes = {"gold": 50, "gems": 30, "empty": 0, "trap": -20}\n\nplayer = Player("Nova")\n\nwhile player.is_playing():\n    chest = random.choice(chests)\n    reward = prizes.get(chest, 0)\n    player.coins = player.coins + reward\n    player.energy = player.energy - 1\n    print("Opened a", chest, "chest ->", reward, "coins")\n\n    if player.coins >= 100:\n        print("Rich enough! Going home early.")\n        break\n\nprint("---")\nprint(player.name, "finished with", player.coins, "coins")',
      expectedOutput: /finished with/,
    },
    {
      type: 'predict',
      id: 'predict-pieces',
      title: 'Name the Pieces',
      question: 'In the treasure hunt above, what is prizes?',
      code: 'prizes = {"gold": 50, "gems": 30, "empty": 0, "trap": -20}\nreward = prizes.get(chest, 0)',
      // Two lines lifted out of the game above, not a program on their own.
      fragment: true,
      choices: [
        'A list, looked up by position',
        'A dictionary, looked up by name',
        'A set, which drops duplicates',
        'A tuple, which cannot change',
      ],
      correct: 1,
      explain: 'Right — curly braces with key: value pairs, and .get() looking one up by name. Lesson 20.',
      wrongHint: 'Look at the brackets, and look at what goes inside them.',
      hints: ['Sets have curly braces too, but no colons.', '.get() with a fallback is a dictionary method.'],
    },
    {
      type: 'tryit',
      id: 'tryit',
      title: 'Make It Yours',
      description: 'Change the chests, change the prizes, change how much energy the player starts with. Break it and fix it — that is the lesson.',
      code: 'import random\n\nchests = ["gold", "empty", "gems", "trap"]\nprizes = {"gold": 50, "gems": 30, "empty": 0, "trap": -20}\n\ncoins = 0\nenergy = 4\n\nwhile energy > 0:\n    chest = random.choice(chests)\n    coins = coins + prizes.get(chest, 0)\n    energy = energy - 1\n    print("Opened", chest, "- coins now", coins)\n\nprint("Final score:", coins)',
      expectedOutput: /Final score:/,
      expectedKeywords: ['while', 'random'],
      wrongOutputHint: 'The last line should announce a final score after the loop ends.',
      hints: [
        'Add a new kind of chest to the list, then give it a value in the prizes dictionary.',
        'What happens if you give a chest a value but forget to add it to the list?',
      ],
    },
    {
      type: 'challenge',
      id: 'challenge',
      title: 'Add a Quiz Round',
      description: 'A quiz built from two lists walked together with zip, marked with a function, wrapped in try. Six lessons in fifteen lines.',
      optional: true,
      code: 'questions = ["2 + 2", "10 / 2", "3 * 3"]\nanswers = [4, 5, 9]\ngiven = ["4", "five", "9"]\n\ndef mark(given_answer, correct_answer):\n    try:\n        return int(given_answer) == correct_answer\n    except ValueError:\n        return False\n\nscore = 0\nfor number, (question, correct, mine) in enumerate(zip(questions, answers, given), start=1):\n    if mark(mine, correct):\n        score = score + 1\n        print(number, question, "- correct")\n    else:\n        print(number, question, "- wrong, the answer was", correct)\n\nprint("Scored", score, "out of", len(questions))',
      expectedOutput: /Scored 2 out of 3/,
      expectedKeywords: ['zip', 'try', 'def'],
      wrongOutputHint: 'Two of the three answers are right, so the score should read 2 out of 3.',
      hints: [
        'zip can take three lists, not just two.',
        '"five" cannot become an int, so the try/except is what stops it crashing the whole quiz.',
      ],
    },
  ],
};

export default lesson31;
