const lesson30 = {
  id: 30,
  title: "Recursion. A Function That Calls Itself",
  subtitle: "The strangest idea in this course, and one of the most useful.",
  emoji: "🪆",
  xp: 50,
  story: "Russian dolls. Each one contains a smaller one, until you reach the tiny one that contains nothing. That last doll is the reason recursion ever stops.",
  steps: [
    {
      type: 'concept',
      id: 'concept',
      title: 'Two Parts, Always',
      body: 'A recursive function calls itself on a smaller version of the problem. It needs a base case. The moment it stops. And a recursive case that gets closer to it. Without the base case it never ends, and Python gives up with a RecursionError.',
      highlight: 'def countdown(n):\n    if n == 0:          # base case: STOP\n        print("Lift off!")\n        return\n    print(n)\n    countdown(n - 1)    # smaller each time',
      code: 'def countdown(n):\n    if n == 0:\n        print("Lift off!")\n        return\n    print(n)\n    countdown(n - 1)\n\ncountdown(3)',
    },
    {
      type: 'predict',
      id: 'predict-base',
      title: 'What Stops It?',
      question: 'This function is missing something. What happens when it runs?',
      code: 'def forever(n):\n    print(n)\n    forever(n - 1)\n\nforever(3)',
      // Deliberately missing its base case, so it runs until Python stops it.
      expectsError: true,
      choices: [
        'It prints 3, 2, 1 and stops',
        'It prints nothing',
        'It prints forever until Python raises RecursionError',
        'It prints 3 once',
      ],
      correct: 2,
      explain: 'Exactly. There is no base case, so nothing ever tells it to stop. Python cuts it off with a RecursionError.',
      wrongHint: 'Look for the line that would make it stop. There is not one.',
      hints: ['Every recursive function needs an if that ends it.', 'Numbers can go negative forever.'],
    },
    {
      type: 'order',
      id: 'order-recursion',
      title: 'Build a Recursive Function',
      question: 'Put these lines together to make a working countdown.',
      shuffled: [
        '    countdown(n - 1)',
        'def countdown(n):',
        '    print(n)',
        '    if n == 0:',
        '        return',
      ],
      correctOrder: [
        'def countdown(n):',
        '    if n == 0:',
        '        return',
        '    print(n)',
        '    countdown(n - 1)',
      ],
      explain: 'That is the shape every recursive function has: check for the stop first, then do the work, then call itself on something smaller.',
      wrongHint: 'The base case has to be checked before anything else, or the function will never get the chance to stop.',
    },
    {
      type: 'example',
      id: 'example',
      title: 'Factorial',
      description: '5 factorial is 5 × 4 × 3 × 2 × 1. Run it and watch the layers unwind.',
      code: 'def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)\n\nfor n in range(1, 6):\n    print(n, "factorial is", factorial(n))',
      expectedOutput: /5 factorial is 120/,
    },
    {
      type: 'tryit',
      id: 'tryit',
      title: 'Add Up a List',
      description: 'The sum of a list is the first item plus the sum of the rest. That sentence is the whole function.',
      code: 'def total(numbers):\n    if len(numbers) == 0:\n        return 0\n    return numbers[0] + total(numbers[1:])\n\nprint(total([1, 2, 3, 4, 5]))',
      expectedOutput: /15/,
      expectedKeywords: ['return', 'total('],
      wrongOutputHint: 'The numbers 1 to 5 add up to 15.',
      hints: [
        'numbers[1:] is everything except the first item. That is the smaller problem.',
        'The base case is an empty list, which adds up to 0.',
      ],
    },
    {
      type: 'challenge',
      id: 'challenge',
      title: 'Reverse a Word',
      description: 'Reversing a word is the last letter, plus the reverse of everything before it.',
      optional: true,
      code: 'def backwards(word):\n    if len(word) <= 1:\n        return word\n    return word[-1] + backwards(word[:-1])\n\nprint(backwards("python"))',
      expectedOutput: /nohtyp/,
      expectedKeywords: ['backwards('],
      wrongOutputHint: 'python reversed is nohtyp.',
      hints: [
        'word[-1] is the last letter; word[:-1] is everything except the last letter.',
        'A word of one letter is already backwards. That is your base case.',
      ],
    },
  ],
};

export default lesson30;
