const lesson20 = {
  id: 20,
  title: "Dictionaries — Labels, Not Numbers",
  subtitle: "A list remembers order. A dictionary remembers names.",
  emoji: "📖",
  xp: 50,
  story: "Your game needs a player with a name, a score and three lives. A list would make you remember that lives live at position 2. A dictionary just calls it 'lives'.",
  steps: [
    {
      type: 'concept',
      id: 'concept',
      title: 'Look It Up By Name',
      body: 'A dictionary stores pairs: a key and its value. You get a value back by asking for its key, not by counting positions. Curly braces make one, and square brackets look inside.',
      highlight: 'player = {"name": "Nova", "score": 40, "lives": 3}\n\nplayer["score"]    # 40\nplayer["lives"] = 2   # change it\nplayer["level"] = 1   # add a brand new one',
      code: 'player = {"name": "Nova", "score": 40, "lives": 3}\nprint(player["name"])\nprint(player["score"])',
    },
    {
      type: 'predict',
      id: 'predict-lookup',
      title: 'What Comes Out?',
      question: 'What does this print?',
      code: 'pet = {"name": "Rex", "legs": 4}\npet["legs"] = 3\nprint(pet["legs"])',
      choices: ['4', '3', 'legs', 'An error'],
      correct: 1,
      explain: 'Right. Assigning to a key that already exists replaces the old value.',
      wrongHint: 'Read the lines in order. The middle line changes something before the print happens.',
      hints: ['pet["legs"] = 3 is not a question, it is a change.', 'The print runs last, after the change.'],
    },
    {
      type: 'fillblank',
      id: 'fill-dict',
      title: 'Build a Player',
      question: 'Make a dictionary for a player called Blaze with 100 health.',
      template: 'player = ___"name": "Blaze", "health": 100___\nprint(player[___])',
      options: ['{', '}', '[', ']', '"health"', 'health'],
      answers: ['{', '}', '"health"'],
      explain: 'Yes — curly braces build the dictionary, and the key needs its quote marks.',
      wrongHint: 'Dictionaries use curly braces. A key made of text needs quote marks around it.',
      hints: [
        'Lists use square brackets. Dictionaries use the curly ones.',
        'Without quotes, health would be a variable name, not the key you stored.',
      ],
    },
    {
      type: 'example',
      id: 'example',
      title: 'A Whole Character Sheet',
      description: 'Run it, then change a value and run it again.',
      code: 'hero = {"name": "Echo", "power": "invisibility", "level": 3}\nprint(hero["name"], "has", hero["power"])\nhero["level"] = hero["level"] + 1\nprint("Levelled up to", hero["level"])',
      expectedOutput: /Levelled up to/,
    },
    {
      type: 'tryit',
      id: 'tryit',
      title: 'Your Own Character',
      description: 'Change the name, the power and the level to make this character yours. Then add one new key of your own.',
      code: 'hero = {"name": "Echo", "power": "invisibility", "level": 3}\nhero["pet"] = "dragon"\nprint(hero["name"], "the level", hero["level"], "hero")\nprint("Pet:", hero["pet"])',
      expectedOutput: /Pet:/,
      expectedKeywords: ['{', '}'],
      wrongOutputHint: 'Keep both prints — one for the hero, one for the new key you added.',
      hints: [
        'Add a key by assigning to it: hero["speed"] = 9',
        'Any word can be a key, as long as it is in quote marks.',
      ],
    },
    {
      type: 'challenge',
      id: 'challenge',
      title: 'A Safe Lookup',
      description: 'Asking for a key that does not exist is an error. .get() hands back a fallback instead of crashing.',
      optional: true,
      code: 'player = {"name": "Nova", "score": 40}\nprint(player.get("score", 0))\nprint(player.get("lives", 3))',
      expectedOutput: /3/,
      expectedKeywords: ['get'],
      wrongOutputHint: 'The second print should show the fallback 3, because there is no "lives" key.',
      hints: [
        '.get(key, fallback) means "give me this, or this if it is missing".',
        'Try player["lives"] instead and see the crash it avoids.',
      ],
    },
  ],
};

export default lesson20;
