const lesson27 = {
  id: 27,
  title: "Try and Except — When Things Go Wrong",
  subtitle: "Catch the crash and keep the program running.",
  emoji: "🛡️",
  xp: 50,
  story: "Someone types 'banana' where your game wanted a number. Without try, the whole thing stops. With try, you smile and ask again.",
  steps: [
    {
      type: 'concept',
      id: 'concept',
      title: 'Attempt, Then Recover',
      body: 'Put the risky code in a try block. If it goes wrong, Python jumps straight to the except block instead of crashing. Name the kind of error you expect, so a different problem is not swallowed silently.',
      highlight: 'try:\n    age = int("banana")\nexcept ValueError:\n    print("That is not a number")\n\n# common ones:\n# ValueError     — the wrong sort of value\n# ZeroDivisionError — divided by zero\n# KeyError       — no such key in a dictionary',
      code: 'try:\n    age = int("banana")\n    print("Age is", age)\nexcept ValueError:\n    print("That is not a number!")\n\nprint("The program is still running.")',
    },
    {
      type: 'predict',
      id: 'predict-try',
      title: 'Which Lines Run?',
      question: 'What does this print?',
      code: 'try:\n    print("A")\n    result = 10 / 0\n    print("B")\nexcept ZeroDivisionError:\n    print("C")\nprint("D")',
      choices: ['A\nB\nC\nD', 'A\nC\nD', 'A\nB\nD', 'A\nC'],
      correct: 1,
      explain: 'Right. A runs, the division fails, B is skipped entirely, C handles it, and D runs because the program survived.',
      wrongHint: 'Once something goes wrong inside try, the rest of the try block is abandoned.',
      hints: [
        'Everything after the failing line inside try is skipped.',
        'Code after the whole try/except still runs, because nothing crashed.',
      ],
    },
    {
      type: 'order',
      id: 'order-try',
      title: 'Assemble the Safety Net',
      question: 'Put these lines into a working try/except.',
      shuffled: [
        'except ValueError:',
        'try:',
        '    print("Please type a number")',
        '    score = int(typed)',
      ],
      correctOrder: [
        'try:',
        '    score = int(typed)',
        'except ValueError:',
        '    print("Please type a number")',
      ],
      explain: 'That is the shape: try first with the risky line inside it, then except with the recovery.',
      wrongHint: 'The risky line goes inside try, and except comes after it, not before.',
    },
    {
      type: 'example',
      id: 'example',
      title: 'A Safe Divider',
      description: 'Run it. The second division would normally kill the program.',
      code: 'def safe_divide(a, b):\n    try:\n        return a / b\n    except ZeroDivisionError:\n        return "Cannot divide by zero"\n\nprint(safe_divide(10, 2))\nprint(safe_divide(10, 0))\nprint("Still here!")',
      expectedOutput: /Still here!/,
    },
    {
      type: 'tryit',
      id: 'tryit',
      title: 'Check Every Answer',
      description: 'Some of these are numbers and some are not. The loop must survive all of them.',
      code: 'answers = ["12", "seven", "30", "x"]\ntotal = 0\nfor answer in answers:\n    try:\n        total = total + int(answer)\n    except ValueError:\n        print("Skipping", answer)\nprint("Total:", total)',
      expectedOutput: /Total: 42/,
      expectedKeywords: ['try', 'except'],
      wrongOutputHint: 'The two real numbers add up to 42, and the other two should be skipped with a message.',
      hints: [
        'int("seven") raises a ValueError — that is the one to catch.',
        'The try goes inside the loop, so one bad answer does not end the whole thing.',
      ],
    },
    {
      type: 'challenge',
      id: 'challenge',
      title: 'Say What Went Wrong',
      description: 'Capture the error itself with "as" so you can show the real reason.',
      optional: true,
      code: 'scores = {"Nova": 40}\n\ntry:\n    print(scores["Blaze"])\nexcept KeyError as problem:\n    print("No such player:", problem)\n\nprint("Carrying on.")',
      expectedOutput: /No such player/,
      expectedKeywords: ['except', 'as'],
      wrongOutputHint: 'The message should name the missing player, then the program should carry on.',
      hints: [
        'A missing dictionary key raises KeyError, not ValueError.',
        '"as problem" gives you the error object to print.',
      ],
    },
  ],
};

export default lesson27;
