const lesson9 = {
  id: 9,
  title: "Basic Functions",
  subtitle: "Write code once, use it many times. Make your own Python commands!",
  emoji: "⚙️",
  story: "When you catch yourself writing the same lines twice, that is the moment to make a function.",
  steps: [
    {
      type: 'concept',
      id: 'concept',
      title: 'Define and Call a Function',
      body: 'A function is a reusable block of code. You define it once with def, then call it by name whenever you need it. You can pass values in (called parameters) and get a value back with return!',
      highlight: 'def greet(name):\n    print("Hello,", name)\n\ngreet("Alex")   →   Hello, Alex\ngreet("Sam")    →   Hello, Sam',
      code: 'def greet(name):\n    print("Hello,", name)\n\ngreet("Alex")\ngreet("Sam")',
    },
    {
      type: 'predict',
      id: 'predict-return',
      title: 'What Comes Back?',
      question: 'What does this print?',
      code: 'def double(n):\n    return n * 2\n\nprint(double(4) + 1)',
      choices: ['8', '9', '10', '4'],
      correct: 1,
      explain: 'Yes. Double(4) hands back 8, and then 1 is added to it.',
      wrongHint: 'Work out what the function gives back first, then do what the rest of the line says.',
      hints: ['double(4) becomes 8.', 'Now read the line again with 8 in place of double(4).'],
    },
    {
      type: 'example',
      id: 'example',
      title: 'Your First Function',
      description: 'Click Run to see a function defined and called twice with different names!',
      code: 'def say_hi(name):\n    print("Hi,", name + "!")\n\nsay_hi("Alex")\nsay_hi("Sam")',
      successPattern: /Hi.*Alex|Hi.*Sam/i,
      hint: 'Click Run! say_hi() is defined once but called twice. Each call uses a different name.',
      xp: 10,
    },
    {
      type: 'tryit',
      id: 'tryit',
      title: 'Function with a Parameter',
      description: 'Run the code, then call greet() with YOUR name as the argument!',
      code: 'def greet(name):\n    print("Hello,", name + "!")\n\ngreet("Alex")',
      successPattern: /Hello/i,
      hint: 'Change "Alex" to your own name and run again. The parameter takes whatever you pass in!',
      xp: 15,
    },
    {
      type: 'challenge',
      id: 'challenge',
      title: 'Function with Return',
      description: 'Run the code to see a function return a value. Then change the numbers!',
      code: 'def add(a, b):\n    return a + b\n\nresult = add(3, 4)\nprint("Sum:", result)',
      successPattern: /Sum:/i,
      hint: 'return sends a value back from the function. Change 3 and 4 to your own numbers!',
      xp: 20,
    },
  ]
};

export default lesson9;
