const lesson17 = {
  id: 17,
  title: "While Loops — Keep Going Until",
  subtitle: "A for loop counts. A while loop waits for something to happen.",
  emoji: "🔁",
  xp: 50,
  story: "Your rocket needs a countdown, but you do not know how long the fuel will last. A while loop keeps going until something changes.",
  steps: [
    {
      type: 'concept',
      id: 'concept',
      title: 'Repeat Until Something Changes',
      body: 'A for loop needs to know how many times to repeat before it starts. A while loop does not. It checks a question at the top of every lap, and keeps looping for as long as the answer is True.',
      highlight: 'fuel = 3\nwhile fuel > 0:      # ask the question\n    print(fuel)\n    fuel = fuel - 1  # change the answer\nprint("Lift off!")',
      code: 'fuel = 3\nwhile fuel > 0:\n    print(fuel)\n    fuel = fuel - 1\nprint("Lift off!")',
    },
    {
      type: 'predict',
      id: 'predict-count',
      title: 'How Many Laps?',
      question: 'What does this print?',
      code: 'lives = 2\nwhile lives > 0:\n    print("Try again")\n    lives = lives - 1',
      choices: [
        'Try again',
        'Try again\nTry again',
        'Try again\nTry again\nTry again',
        'Nothing at all',
      ],
      correct: 1,
      explain: 'Right — lives starts at 2, so the loop runs twice and then 0 > 0 is False.',
      wrongHint: 'Count the laps. lives is 2, then 1, then 0. The loop stops as soon as the question is False.',
      hints: [
        'The loop checks "is lives more than 0?" before every single lap.',
        'Write down lives after each lap: 2 → 1 → 0. How many times did it print before reaching 0?',
      ],
    },
    {
      type: 'fillblank',
      id: 'fill-loop',
      title: 'Build the Loop',
      question: 'Finish this loop so it counts down from 5 and stops.',
      template: 'count = 5\n___ count > 0:\n    print(count)\n    count = count ___ 1',
      options: ['while', 'if', '-', '+'],
      answers: ['while', '-'],
      explain: 'Exactly. Without the subtraction, count never reaches 0 and the loop never ends.',
      wrongHint: 'One piece starts the loop, the other makes count get smaller each lap.',
      hints: [
        'The first gap is the word that means "keep repeating".',
        'If count never gets smaller, the loop runs forever. Which sign makes a number shrink?',
      ],
    },
    {
      type: 'example',
      id: 'example',
      title: 'Watch It Run',
      description: 'Click Run. Watch the number shrink until the loop gives up.',
      code: 'fuel = 5\nwhile fuel > 0:\n    print("Fuel:", fuel)\n    fuel = fuel - 1\nprint("Lift off!")',
      expectedOutput: /Lift off!/,
    },
    {
      type: 'tryit',
      id: 'tryit',
      title: 'Double It Until It Passes 100',
      description: 'Start at 1 and keep doubling until the number is bigger than 100. Change the starting number and see what happens.',
      code: 'number = 1\nwhile number <= 100:\n    print(number)\n    number = number * 2\nprint("Passed 100 with", number)',
      expectedOutput: /Passed 100 with/,
      expectedKeywords: ['while'],
      wrongOutputHint: 'The last line should say how big the number got. Keep the print at the end.',
      hints: [
        'The loop condition is "while number is 100 or less".',
        'Try starting at 3 instead of 1 — the numbers change but the loop still stops.',
      ],
    },
    {
      type: 'challenge',
      id: 'challenge',
      title: 'Guessing Game',
      description: 'A secret number, and a guesser that creeps up one at a time. Change the secret and run again.',
      optional: true,
      code: 'secret = 7\nguess = 1\nwhile guess != secret:\n    print("Guessing", guess)\n    guess = guess + 1\nprint("Found it! The secret was", secret)',
      expectedOutput: /Found it!/,
      expectedKeywords: ['while'],
      wrongOutputHint: 'The last line should announce the secret. Make sure the loop stops when guess matches it.',
      hints: [
        '!= means "is not equal to". The loop runs while the guess is wrong.',
        'Careful: if secret is smaller than the starting guess, the loop can never catch it.',
      ],
    },
  ],
};

export default lesson17;
