const lesson24 = {
  id: 24,
  title: "List Comprehensions. A List in One Line",
  subtitle: "The shortcut every Python programmer uses.",
  emoji: "⚡",
  xp: 50,
  story: "You already know how to build a list with a loop. This is the same thing, written the way working Python programmers actually write it.",
  steps: [
    {
      type: 'concept',
      id: 'concept',
      title: 'The Same Loop, Squashed',
      body: 'Four lines of loop become one line inside square brackets. Read it out loud in order: the thing you want, then for each item, then the list it comes from. You can add an if on the end to keep only some of them.',
      highlight: '# the long way\ndoubles = []\nfor n in numbers:\n    doubles.append(n * 2)\n\n# the same thing\ndoubles = [n * 2 for n in numbers]\n\n# only the big ones\nbig = [n for n in numbers if n > 10]',
      code: 'numbers = [1, 2, 3, 4, 5]\ndoubles = [n * 2 for n in numbers]\nprint(doubles)',
    },
    {
      type: 'predict',
      id: 'predict-comp',
      title: 'Read It Out Loud',
      question: 'What does this print?',
      code: 'numbers = [1, 2, 3, 4]\nresult = [n * n for n in numbers]\nprint(result)',
      choices: ['[1, 2, 3, 4]', '[2, 4, 6, 8]', '[1, 4, 9, 16]', '[1, 2, 3, 4, 1, 2, 3, 4]'],
      correct: 2,
      explain: 'Yes. Each number multiplied by itself: 1, 4, 9, 16.',
      wrongHint: 'n * n is n multiplied by itself, not n added to itself.',
      hints: ['Work it out for one number first: what is 3 * 3?', 'Now do that for every number in the list.'],
    },
    {
      type: 'fillblank',
      id: 'fill-comp',
      title: 'Keep Only the Big Ones',
      question: 'Build a list of only the scores above 50.',
      template: 'scores = [30, 72, 45, 91]\nhigh = [s ___ s in scores ___ s > 50]\nprint(high)',
      options: ['for', 'in', 'if', 'while'],
      answers: ['for', 'if'],
      explain: 'Exactly. The for walks the list, and the if decides what makes the cut.',
      wrongHint: 'One word walks through the list. The other filters what gets kept.',
      hints: [
        'Read it as a sentence: "s, for each s in scores, if s is more than 50".',
        'The filter always goes at the end.',
      ],
    },
    {
      type: 'order',
      id: 'order-comp',
      title: 'Rebuild It the Long Way',
      question: 'These lines do the same job as [n * 2 for n in numbers]. Put them in order.',
      shuffled: [
        '    doubles.append(n * 2)',
        'doubles = []',
        'for n in numbers:',
        'print(doubles)',
      ],
      correctOrder: [
        'doubles = []',
        'for n in numbers:',
        '    doubles.append(n * 2)',
        'print(doubles)',
      ],
      explain: 'That is the long version. Both do exactly the same thing. The one-liner is just quicker to write.',
      wrongHint: 'You need an empty list before you can append to it, and the append belongs inside the loop.',
    },
    {
      type: 'tryit',
      id: 'tryit',
      title: 'Shout Every Name',
      description: 'Build a new list with every name in capitals, in one line.',
      code: 'names = ["nova", "blaze", "echo"]\nshouted = [name.upper() for name in names]\nprint(shouted)',
      expectedOutput: /NOVA/,
      expectedKeywords: ['for', 'upper'],
      wrongOutputHint: 'All three names should come out in capitals.',
      hints: [
        '.upper() turns a string into capitals.',
        'The thing you want goes first, before the for.',
      ],
    },
    {
      type: 'challenge',
      id: 'challenge',
      title: 'Even Squares Only',
      description: 'From 1 to 10, square each number but keep only the even results.',
      optional: true,
      code: 'result = [n * n for n in range(1, 11) if (n * n) % 2 == 0]\nprint(result)',
      expectedOutput: /\[4, 16, 36, 64, 100\]/,
      expectedKeywords: ['for', 'if'],
      wrongOutputHint: 'You should get [4, 16, 36, 64, 100].',
      hints: [
        'Square first, then test whether the square is even.',
        'A number is even when dividing by 2 leaves a remainder of 0.',
      ],
    },
  ],
};

export default lesson24;
