const lesson19 = {
  id: 19,
  title: "Import and Random. Borrowing Superpowers",
  subtitle: "Python comes with toolboxes. Import opens one.",
  emoji: "🎲",
  xp: 50,
  story: "No game is fun if it does the same thing every time. Random is how you roll a dice, shuffle a deck, or pick a surprise.",
  steps: [
    {
      type: 'concept',
      id: 'concept',
      title: 'Somebody Already Wrote It',
      body: 'You do not have to build everything yourself. Python ships with modules. Ready-made toolboxes of code. Import brings one into your program, and then you use its tools with a dot.',
      highlight: 'import random\n\nrandom.randint(1, 6)      # a whole number, 1 to 6\nrandom.choice(["a", "b"])  # one item from a list',
      code: 'import random\n\ndice = random.randint(1, 6)\nprint("You rolled", dice)',
    },
    {
      type: 'fillblank',
      id: 'fill-import',
      title: 'Open the Toolbox',
      question: 'Finish this so it picks a random hero from the list.',
      template: '___ random\n\nheroes = ["Nova", "Blaze", "Echo"]\npicked = random.___(heroes)\nprint(picked)',
      options: ['import', 'from', 'choice', 'randint'],
      answers: ['import', 'choice'],
      explain: 'That is it. Randint gives you a number; choice picks an item out of a list.',
      wrongHint: 'One word opens the toolbox. The other is the tool that picks from a list.',
      hints: [
        'The first line is how every module gets brought in.',
        'You are picking from a list, not making up a number.',
      ],
    },
    {
      type: 'example',
      id: 'example',
      title: 'Roll the Dice',
      description: 'Run this a few times. The number changes. That is the point.',
      code: 'import random\n\nfor roll in range(5):\n    print("Roll", roll + 1, ":", random.randint(1, 6))',
      expectedOutput: /Roll/,
    },
    {
      type: 'concept',
      id: 'concept-math',
      title: 'The Maths Toolbox Too',
      body: 'random is not the only one. Math holds things like pi and square roots. Every module works the same way: import it, then reach for its tools with a dot.',
      highlight: 'import math\n\nmath.pi          # 3.14159...\nmath.sqrt(16)    # 4.0\nmath.floor(2.7)  # 2',
      code: 'import math\n\nprint("Pi is about", round(math.pi, 2))\nprint("The square root of 81 is", math.sqrt(81))\nprint("2.7 rounded down is", math.floor(2.7))',
    },
    {
      type: 'tryit',
      id: 'tryit',
      title: 'A Magic 8-Ball',
      description: 'Pick a random answer from the list. Add your own answers and run it again.',
      code: 'import random\n\nanswers = ["Definitely", "Ask again later", "No way", "It is certain"]\nprint("The 8-ball says:", random.choice(answers))',
      expectedOutput: /8-ball says/,
      expectedKeywords: ['import', 'random', 'choice'],
      wrongOutputHint: 'Keep the "The 8-ball says:" message and let random.choice pick the answer.',
      hints: [
        'random.choice takes a list and hands back one item from it.',
        'Add a fifth answer to the list. The 8-ball can now say it too.',
      ],
    },
    {
      type: 'challenge',
      id: 'challenge',
      title: 'Two Dice, One Total',
      description: 'Roll two dice, print each one, then print the total.',
      optional: true,
      code: 'import random\n\nfirst = random.randint(1, 6)\nsecond = random.randint(1, 6)\nprint("First:", first)\nprint("Second:", second)\nprint("Total:", first + second)',
      expectedOutput: /Total:/,
      expectedKeywords: ['randint'],
      wrongOutputHint: 'You need three lines of output: first die, second die, and the total.',
      hints: [
        'Call random.randint twice and store each result in its own variable.',
        'The total is just the two variables added together.',
      ],
    },
  ],
};

export default lesson19;
