const lesson23 = {
  id: 23,
  title: "Slicing — Taking a Piece",
  subtitle: "Grab part of a list or part of a word, without touching the rest.",
  emoji: "✂️",
  xp: 50,
  story: "The top three scores. The first letter of a name. The last item in a shopping list. All of them are one slice away.",
  steps: [
    {
      type: 'concept',
      id: 'concept',
      title: 'Start, Stop, Step',
      body: 'A slice uses square brackets with a colon: [start:stop]. It begins at start and stops just before stop. Leave a side empty to mean "all the way". A negative number counts backwards from the end.',
      highlight: 'scores = [10, 20, 30, 40, 50]\n\nscores[0:3]   # [10, 20, 30]  — stops BEFORE 3\nscores[:2]    # [10, 20]      — from the start\nscores[3:]    # [40, 50]      — to the end\nscores[-1]    # 50            — the last one',
      code: 'scores = [10, 20, 30, 40, 50]\nprint(scores[0:3])\nprint(scores[-1])',
    },
    {
      type: 'predict',
      id: 'predict-slice',
      title: 'Where Does It Stop?',
      question: 'What does this print?',
      code: 'letters = ["a", "b", "c", "d", "e"]\nprint(letters[1:4])',
      choices: [
        "['a', 'b', 'c', 'd']",
        "['b', 'c', 'd']",
        "['b', 'c', 'd', 'e']",
        "['a', 'b', 'c']",
      ],
      correct: 1,
      explain: 'Right. It starts at position 1 and stops just before position 4 — so b, c and d.',
      wrongHint: 'Counting starts at 0, and the stop number is not included.',
      hints: [
        'Position 0 is "a", position 1 is "b".',
        'The stop number says where to stop, not what to include.',
      ],
    },
    {
      type: 'fillblank',
      id: 'fill-top3',
      title: 'Top Three Only',
      question: 'Take just the first three scores from this list.',
      template: 'scores = [95, 88, 74, 60, 51]\ntop = scores[___:___]\nprint(top)',
      options: ['0', '1', '3', '4'],
      answers: ['0', '3'],
      explain: 'Correct — start at the beginning, stop just before position 3, which gives you three items.',
      wrongHint: 'You want the first three. Where does counting start, and where must it stop?',
      hints: ['Lists start counting at 0.', 'To get three items starting at 0, the stop number is 3.'],
    },
    {
      type: 'example',
      id: 'example',
      title: 'Slicing Words Too',
      description: 'Strings slice exactly like lists. Run it.',
      code: 'name = "Python"\nprint(name[0])\nprint(name[0:3])\nprint(name[-2:])\nprint(name[::-1])',
      expectedOutput: /nohtyP/,
    },
    {
      type: 'tryit',
      id: 'tryit',
      title: 'Initials',
      description: 'Take the first letter of each name to build a set of initials.',
      code: 'first = "Ada"\nlast = "Lovelace"\ninitials = first[0] + "." + last[0] + "."\nprint(initials)',
      expectedOutput: /A\.L\./,
      expectedKeywords: ['[0]'],
      wrongOutputHint: 'You want A.L. — take position 0 from each name.',
      hints: [
        'name[0] is the very first character.',
        'Try it with your own name and your family name.',
      ],
    },
    {
      type: 'challenge',
      id: 'challenge',
      title: 'Is It a Palindrome?',
      description: 'A palindrome reads the same backwards. Slice with a step of -1 to reverse a word and compare.',
      optional: true,
      code: 'word = "racecar"\nbackwards = word[::-1]\nprint(backwards)\nprint(word == backwards)',
      expectedOutput: /True/,
      expectedKeywords: ['[::-1]'],
      wrongOutputHint: 'The second line should print True for racecar. Check the step of -1.',
      hints: [
        '[::-1] means "everything, stepping backwards by one".',
        'Try "hello" instead — it prints False.',
      ],
    },
  ],
};

export default lesson23;
