const lesson21 = {
  id: 21,
  title: "Looping Through a Dictionary",
  subtitle: "Visit every label and every value, one pair at a time.",
  emoji: "🔑",
  xp: 50,
  story: "You have a scoreboard for the whole class. Printing them one at a time would take all day. A loop does it in three lines.",
  steps: [
    {
      type: 'concept',
      id: 'concept',
      title: 'Three Ways to Walk Through',
      body: 'Looping over a dictionary gives you the keys. .values() gives you the values instead. .items() gives you both at once, which is usually the one you want.',
      highlight: 'for key in scores:            # just the names\nfor value in scores.values(): # just the numbers\nfor key, value in scores.items():  # both',
      code: 'scores = {"Nova": 40, "Blaze": 65, "Echo": 22}\nfor name, points in scores.items():\n    print(name, "scored", points)',
    },
    {
      type: 'order',
      id: 'order-loop',
      title: 'Put the Scoreboard Together',
      question: 'These lines print a scoreboard, but they are jumbled. Put them in the right order.',
      shuffled: [
        'for name, points in scores.items():',
        'scores = {"Nova": 40, "Blaze": 65}',
        'print("--- Scoreboard ---")',
        '    print(name, ":", points)',
      ],
      correctOrder: [
        'scores = {"Nova": 40, "Blaze": 65}',
        'print("--- Scoreboard ---")',
        'for name, points in scores.items():',
        '    print(name, ":", points)',
      ],
      explain: 'Exactly. Make the data, print the heading, then loop. The indented line has to come after the for that owns it.',
      wrongHint: 'You cannot loop over scores before scores exists. And the indented line belongs inside the loop.',
    },
    {
      type: 'predict',
      id: 'predict-keys',
      title: 'Keys or Values?',
      question: 'What does this print?',
      code: 'ages = {"Sam": 9, "Ada": 11}\nfor thing in ages:\n    print(thing)',
      choices: ['9\n11', 'Sam\nAda', 'Sam 9\nAda 11', 'An error'],
      correct: 1,
      explain: 'Correct. Looping over a dictionary on its own gives you the keys.',
      wrongHint: 'Without .values() or .items(), a plain loop over a dictionary hands you the labels.',
      hints: ['There is no .values() or .items() here.', 'Python picks the keys as the sensible default.'],
    },
    {
      type: 'example',
      id: 'example',
      title: 'Add Up Every Score',
      description: 'Run it. The loop adds each value to a running total.',
      code: 'scores = {"Nova": 40, "Blaze": 65, "Echo": 22}\ntotal = 0\nfor points in scores.values():\n    total = total + points\nprint("Total points:", total)',
      expectedOutput: /Total points: 127/,
    },
    {
      type: 'tryit',
      id: 'tryit',
      title: 'Find the Winner',
      description: 'Loop through the scores and keep track of who is in the lead.',
      code: 'scores = {"Nova": 40, "Blaze": 65, "Echo": 22}\nbest_name = ""\nbest_score = 0\nfor name, points in scores.items():\n    if points > best_score:\n        best_score = points\n        best_name = name\nprint("Winner:", best_name, "with", best_score)',
      expectedOutput: /Winner: Blaze/,
      expectedKeywords: ['items'],
      wrongOutputHint: 'The winner should be Blaze with 65. Check the comparison inside the loop.',
      hints: [
        'Keep two variables: the best name so far and the best score so far.',
        'Every time you find a bigger score, update both of them.',
      ],
    },
    {
      type: 'challenge',
      id: 'challenge',
      title: 'Give Everyone a Bonus',
      description: 'Add 10 points to every player, then print the new scoreboard.',
      optional: true,
      code: 'scores = {"Nova": 40, "Blaze": 65, "Echo": 22}\nfor name in scores:\n    scores[name] = scores[name] + 10\nfor name, points in scores.items():\n    print(name, "now has", points)',
      expectedOutput: /now has 50/,
      expectedKeywords: ['for'],
      wrongOutputHint: 'Nova should end on 50, Blaze on 75, Echo on 32.',
      hints: [
        'Loop over the keys, then change scores[name] for each one.',
        'Two loops is fine here: one to change, one to print.',
      ],
    },
  ],
};

export default lesson21;
