const lesson6 = {
  id: 6,
  title: "For Loops",
  subtitle: "Loop through every letter or item. Let Python do the stepping!",
  emoji: "🔄",
  story: "Every letter of a word, one at a time. That is how a spelling game or a secret decoder works.",
  steps: [
    {
      type: 'concept',
      id: 'concept',
      title: 'Loop Through a String',
      body: 'You can use a for loop to visit every character in a string, one at a time. Python steps through each letter automatically. You just write what to do with each one!',
      highlight: 'for char in "hello":\n    print(char)   →   h  e  l  l  o  (one per line)',
      code: 'for char in "hello":\n    print(char)',
    },
    {
      type: 'predict',
      id: 'predict-chars',
      title: 'One Letter At A Time',
      question: 'What does this print?',
      code: 'for letter in "cat":\n    print(letter)',
      choices: ['cat', 'c\na\nt', 'c a t', '3'],
      correct: 1,
      explain: 'Yes. Looping over a word hands you one character per lap.',
      wrongHint: 'The loop runs once for each letter, and each print gets its own line.',
      hints: ['How many letters are in "cat"?', 'That is how many times the loop runs.'],
    },
    {
      type: 'example',
      id: 'example',
      title: 'Loop Through Letters',
      description: 'Click Run to see Python print each letter in "Python" one at a time!',
      code: 'for char in "Python":\n    print(char)',
      expectedOutput: /P[\s\S]*n/,
      hint: 'Click Run! The loop visits every letter in the word "Python" one at a time.',
      xp: 10,
    },
    {
      type: 'tryit',
      id: 'tryit',
      title: 'Loop Through Your Name',
      description: 'Change "Alex" to YOUR name and run. See each letter printed on its own line!',
      code: 'name = "Alex"\nfor char in name:\n    print(char)',
      expectedKeywords: ['for', 'in'],
      wrongOutputHint: 'Keep the for loop. That is what walks through the letters one at a time.',
      hint: 'Change "Alex" to your own name, then click Run to see your letters one by one!',
      xp: 15,
    },
    {
      type: 'challenge',
      id: 'challenge',
      title: 'Loop with If',
      description: 'Run this to see only the vowels in a word. Try changing "Python" to another word!',
      code: 'word = "Python"\nfor char in word:\n    if char in "aeiouAEIOU":\n        print(char, "is a vowel")',
      successPattern: /vowel/i,
      hint: 'The if checks whether each character is a vowel. Change "Python" to another word!',
      xp: 20,
    },
  ]
};

export default lesson6;
