'use strict';

/**
 * The sitemap said 2026-08-25 on every one of its 69 URLs, and it said it on
 * 26, 27, 28 and 29 August too, through a dozen merges.
 *
 * The cause was not the hand-typed date this project already fixed once. It was
 * the fallback written for that fix. commitDate() shells out to git, and Vercel
 * does not build from a git clone — it unpacks a source archive — so git throws
 * on every production build and the pinned constant is what ships. Locally git
 * works, so every check anyone ran locally passed.
 *
 * A URL's date now comes from a fingerprint of that URL's own content, held in
 * a checked-in manifest. These tests run the git-less case for real, in a child
 * process with git removed from PATH, because that is the only case that was
 * ever broken and the only one a local run cannot see.
 */

const test = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('node:child_process');

const SCRIPT = path.resolve(__dirname, 'generate-static-seo.js');
const MANIFEST = path.resolve(__dirname, '../src/data/contentDates.json');

/** Run a snippet against the generator with git unreachable. */
function withoutGit(snippet, manifestPath) {
  const bin = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'nogit-')), 'bin');
  fs.mkdirSync(bin, { recursive: true });
  return JSON.parse(
    execFileSync(process.execPath, ['-e', `const g = require(${JSON.stringify(SCRIPT)});${snippet}`], {
      encoding: 'utf8',
      env: {
        ...process.env,
        PATH: bin, // an empty directory: no git on it
        ...(manifestPath ? { CODEIT_CONTENT_DATES: manifestPath } : {}),
      },
    }).trim()
  );
}

test('the manifest exists and every entry is a fingerprint and a real date', () => {
  const manifest = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
  const routes = Object.keys(manifest);
  assert.ok(routes.length > 50, `manifest covers only ${routes.length} routes`);
  for (const route of routes) {
    assert.match(manifest[route].hash, /^[0-9a-f]{16}$/, `${route} has no fingerprint`);
    assert.match(manifest[route].date, /^\d{4}-\d{2}-\d{2}$/, `${route} has no ISO date`);
  }
});

test('with no git, every undated page announces its stored date, not the pin', () => {
  // The production condition, checked against the manifest rather than against
  // variety. An earlier version of this test asserted that more than one date
  // appeared, which passed with the fix removed (guides and blog posts carry
  // their own dates and supplied the variety on their own) and then failed with
  // the fix in place on the day the manifest was created, when every page
  // legitimately shared one date. Neither outcome had anything to do with the
  // bug. What matters is where the date comes from.
  const pages = withoutGit(
    'console.log(JSON.stringify(' +
      '[g.HOME_PAGE, ...g.PAGES]' +
      '.filter((p) => !/^\\d{4}-\\d{2}-\\d{2}$/.test(p.datePublished || ""))' +
      '.map((p) => ({ route: p.route || "/", date: g.pageLastModified(p) }))))'
  );
  assert.ok(pages.length > 20, `only ${pages.length} undated pages were examined`);

  const manifest = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
  for (const { route, date } of pages) {
    const stored = manifest[route];
    assert.ok(stored, `${route} is missing from the manifest`);
    assert.equal(
      date,
      stored.date,
      `${route} announced ${date} on a git-less build instead of its stored ${stored.date}`
    );
  }
});

test('a page whose content changed announces today, not its stored date', () => {
  // Corrupt one fingerprint in a copy of the manifest. That is what a real
  // content edit looks like to this code, and the date must move.
  const manifest = JSON.parse(fs.readFileSync(MANIFEST, 'utf8'));
  const route = Object.keys(manifest).find((r) => r !== '/' && manifest[r]);
  manifest[route] = { hash: '0000000000000000', date: '2001-01-01' };

  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'cdates-'));
  const file = path.join(dir, 'contentDates.json');
  fs.writeFileSync(file, JSON.stringify(manifest));

  const [today, announced] = withoutGit(
    `const p = [g.HOME_PAGE, ...g.PAGES].find((x) => (x.route || '/') === ${JSON.stringify(route)});` +
      'console.log(JSON.stringify([g.BUILD_DATE, p.datePublished || g.pageLastModified(p)]))',
    file
  );

  assert.notEqual(announced, '2001-01-01', `${route} kept a stale date after its content changed`);
  assert.equal(announced, today, `${route} announced ${announced} rather than the build date`);
});

test('the manifest is regenerated by the build, not maintained by hand', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'cdates-'));
  const file = path.join(dir, 'contentDates.json');
  fs.writeFileSync(file, '{}');

  const written = withoutGit('g.writeContentDates();console.log(JSON.stringify(1))', file);
  assert.equal(written, 1);

  const produced = JSON.parse(fs.readFileSync(file, 'utf8'));
  assert.ok(
    Object.keys(produced).length > 50,
    'the build did not rewrite the manifest, so it will go stale the way the typed date did'
  );
});
