-- ── Unlisted projects: a share link that needs no account ────────────────────
--
-- Run this once from the Supabase SQL Editor. The application's database role
-- cannot execute DDL by design, so this is the correct path.
--
-- WHY THIS TABLE IS SEPARATE FROM ai_projects, and why it collects nothing:
--
-- The brief asked for "no account required to save, email only", with the
-- result published at a public /project/:pub URL. That combination cannot ship
-- as written. CodeIt's own policy is that learners aged 5 to 12 use
-- parent-managed profiles which CANNOT publish publicly, and real consent is
-- recorded in adult_email_verifications with a version and a timestamp. An
-- email typed into a box by an anonymous visitor is not verifiable parental
-- consent, and a public URL minted without a check is a side door around
-- public_sharing_allowed.
--
-- So: an unlisted project collects NO personal information at all. There is no
-- email column here on purpose. The secret in the URL is the only credential,
-- the page is noindex, and the project never appears in /explore or any feed.
-- No personal data means no consent to obtain, which is both safer and LESS
-- friction than the brief (zero required fields instead of one).
--
-- An unlisted project can be claimed later: when a signed-in learner opens
-- their own unlisted link, the app offers to copy it into their account, and
-- claimed_by_user_id records that it happened.

create table if not exists public.unlisted_projects (
  id              bigint generated by default as identity primary key,
  public_id       varchar(24) not null unique,
  title           varchar(120) not null,
  project_type    varchar(60),
  generated_code  text not null,
  -- Free text the maker chose to show beside their work. Never required, capped
  -- short, and explicitly not an identifier: the UI asks for "a name for your
  -- work", not for the child's name.
  display_label   varchar(40),
  created_at      timestamptz not null default now(),
  last_seen_at    timestamptz not null default now(),
  view_count      integer not null default 0,
  claimed_by_user_id integer references public.users(user_id) on delete set null,
  -- Anyone can report a link. A reported project stops rendering immediately
  -- and waits for review rather than staying up while a queue drains.
  reported        boolean not null default false
);

create index if not exists idx_unlisted_public_id on public.unlisted_projects(public_id);
create index if not exists idx_unlisted_created  on public.unlisted_projects(created_at);

alter table public.unlisted_projects enable row level security;
