-- CodeIt Plus billing.
--
-- Additive only: no existing table, column, row or index is touched, so this is
-- safe to run against the live database with learner progress in it.
--
-- The subscription row is the single source of truth for paid access, and only
-- the Stripe webhook writes it. Nothing the browser sends can grant a plan.
-- No card details are ever stored here — only Stripe's own identifiers.

create table if not exists public.subscriptions (
  id                     bigint generated by default as identity primary key,
  user_id                integer not null unique references public.users(user_id) on delete cascade,
  stripe_customer_id     varchar(64),
  stripe_subscription_id varchar(64) unique,
  price_id               varchar(64),
  status                 varchar(32) not null default 'incomplete',
  current_period_end     timestamptz,
  cancel_at_period_end   boolean not null default false,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

create index if not exists idx_subscriptions_customer on public.subscriptions(stripe_customer_id);
create index if not exists idx_subscriptions_status on public.subscriptions(status);

-- Stripe retries a webhook until it gets a 2xx, and may deliver the same event
-- more than once even after success. Recording the id makes replay a no-op.
create table if not exists public.billing_events (
  event_id    varchar(80) primary key,
  event_type  varchar(80) not null,
  received_at timestamptz not null default now()
);

create index if not exists idx_billing_events_received on public.billing_events(received_at);

-- One row per AI generation, so the free monthly allowance can be counted per
-- account. Kept separate from ai_usage_events, which records provider cost with
-- no user attribution.
create table if not exists public.ai_build_usage (
  id         bigint generated by default as identity primary key,
  user_id    integer not null references public.users(user_id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists idx_ai_build_usage_user on public.ai_build_usage(user_id, created_at);

-- Postgres has no "create trigger if not exists", so drop first to keep this
-- migration safe to re-run.
drop trigger if exists set_subscriptions_updated_at on public.subscriptions;
create trigger set_subscriptions_updated_at before update on public.subscriptions
for each row execute function public.set_updated_at();

-- Same posture as every other table: the public Data API is denied, and the
-- trusted backend connects directly. Billing rows are the last thing that
-- should ever be reachable from a browser.
alter table public.subscriptions  enable row level security;
alter table public.billing_events enable row level security;
alter table public.ai_build_usage enable row level security;
