-- Evidence that survives the browser.
--
-- Additive only: no existing table, column, row or index is touched, so this
-- is safe to run against the live database with learner progress in it.
--
-- Why this table exists: when a child explains their own project on the Keep
-- page, the record of what they showed lived in one localStorage key. It
-- vanished when a school wiped the browser, a parent could not see it on
-- their phone, and nobody could count it. The comprehension evidence is the
-- thing no competitor has — and it lived in one browser on one device.
--
-- One row per (learner, project). Explaining the same project again merges
-- into the same row rather than stacking: the same game explained twice is
-- not twice the evidence. The skills column holds the server-written
-- sentences as JSON; the client only ever posts question ids, and the wording
-- is written by understandingRecords.js on the backend, so a forged request
-- can claim nothing the studio does not actually ask.

create table if not exists public.understanding_records (
  id            bigint generated by default as identity primary key,
  user_id       integer not null references public.users(user_id) on delete cascade,
  project_key   varchar(80) not null,
  project_title varchar(120) not null,
  skills        jsonb not null default '[]'::jsonb,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint uq_understanding_user_project unique (user_id, project_key)
);

create index if not exists idx_understanding_user on public.understanding_records(user_id);

-- Same posture as every other table: the public Data API is denied and the
-- trusted backend connects directly. A browser must never be able to write
-- its own evidence rows.
alter table public.understanding_records enable row level security;
