-- CodeIt production schema for Supabase PostgreSQL.
-- Tables intentionally use lower-case names so existing unquoted SQL remains compatible.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.users (
  user_id integer generated by default as identity primary key,
  username varchar(50) unique,
  name varchar(255) not null,
  email varchar(255) unique,
  password varchar(255) not null,
  role varchar(50) not null default 'student',
  dob date,
  parent_email varchar(255),
  created_at timestamptz default now(),
  total_xp integer default 0,
  weekly_xp integer default 0,
  level_id integer default 1,
  is_admin smallint not null default 0 check (is_admin in (0, 1))
);

create table public.students (
  student_id integer generated by default as identity primary key,
  user_id integer not null unique references public.users(user_id) on delete cascade,
  created_at timestamptz default now(),
  level_id integer default 1,
  total_xp integer default 0,
  weekly_xp integer default 0,
  current_streak integer not null default 0,
  longest_streak integer not null default 0,
  last_active_date date
);

create table public.lessons (
  id integer generated by default as identity primary key,
  title varchar(255) not null,
  description text not null,
  content text,
  example_code text,
  starter_code text,
  expected_output varchar(1000),
  hints text,
  level varchar(50) not null default 'beginner',
  xp integer not null default 50
);

create table public.puzzles (
  id integer generated by default as identity primary key,
  name varchar(255) not null,
  emoji varchar(10) not null,
  difficulty varchar(50) not null,
  xp integer not null default 100
);

create table public.quiz_questions (
  question_id integer generated by default as identity primary key,
  quiz_id integer not null,
  question_text text not null,
  option_a varchar(255) not null,
  option_b varchar(255) not null,
  option_c varchar(255) not null,
  option_d varchar(255) not null,
  correct_option char(1) not null,
  explanation text,
  created_at timestamptz default now()
);
create index idx_quiz_questions_quiz on public.quiz_questions(quiz_id);

create table public.student_lesson_progress (
  id integer generated by default as identity primary key,
  user_id integer not null,
  lesson_id integer not null,
  xp_earned integer not null default 0,
  completed_at timestamptz default now(),
  constraint uq_user_lesson unique (user_id, lesson_id)
);

create table public.student_puzzle_progress (
  id integer generated by default as identity primary key,
  user_id integer not null,
  puzzle_id integer not null,
  xp_earned integer not null default 0,
  completed_at timestamptz default now(),
  constraint uq_user_puzzle unique (user_id, puzzle_id)
);

create table public.student_quiz_attempt (
  attempt_id integer generated by default as identity primary key,
  student_id integer not null,
  quiz_id integer not null,
  correct_count integer default 0,
  total_questions integer default 0,
  xp_earned integer default 0,
  completed_at timestamptz default now()
);
create index idx_student_quiz_attempt_student on public.student_quiz_attempt(student_id);
create index idx_student_quiz_attempt_quiz on public.student_quiz_attempt(quiz_id);

create table public.parent_notification_log (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(user_id) on delete cascade,
  notification_type varchar(40) not null check (notification_type in ('first_lesson', 'lesson_milestone', 'journey_complete')),
  milestone_value integer not null,
  parent_email varchar(255) not null,
  sent_at timestamptz default now(),
  constraint uq_user_milestone unique (user_id, notification_type, milestone_value)
);

create table public.student_achievement (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(user_id) on delete cascade,
  achievement_key varchar(60) not null,
  label varchar(120) not null default '',
  earned_at timestamptz default now(),
  constraint uq_user_achievement unique (user_id, achievement_key)
);

create table public.student_game_score (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(user_id) on delete cascade,
  game_key varchar(50) not null,
  high_score integer not null default 0,
  updated_at timestamptz default now(),
  constraint uq_user_game unique (user_id, game_key)
);

create table public.user_character (
  user_id integer primary key references public.users(user_id) on delete cascade,
  gender varchar(20) not null default 'female',
  skin_tone varchar(20) not null default 'sunset',
  hair_style varchar(20) not null default 'wave',
  hair_color varchar(20) not null default 'mocha',
  outfit varchar(20) not null default 'astronaut',
  accent varchar(20) not null default 'headphones',
  expression varchar(20) not null default 'smile',
  nickname varchar(50) not null default '',
  updated_at timestamptz default now()
);

create table public.adult_email_verifications (
  user_id integer primary key references public.users(user_id) on delete cascade,
  email varchar(255) not null,
  verified_at timestamptz,
  token_hash char(64),
  expires_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index idx_adult_verification_token on public.adult_email_verifications(token_hash);

create table public.parent_child_links (
  adult_user_id integer not null references public.users(user_id) on delete cascade,
  child_user_id integer not null unique references public.users(user_id) on delete cascade,
  relationship varchar(20) not null,
  consent_version varchar(30) not null,
  consented_at timestamptz default now(),
  public_sharing_allowed smallint not null default 0 check (public_sharing_allowed in (0, 1)),
  progress_emails_enabled smallint not null default 0 check (progress_emails_enabled in (0, 1)),
  primary key (adult_user_id, child_user_id)
);
create index idx_family_adult on public.parent_child_links(adult_user_id);

create table public.legacy_parent_reviews (
  child_user_id integer primary key references public.users(user_id) on delete cascade,
  parent_email varchar(255) not null,
  token_hash char(64),
  expires_at timestamptz,
  status varchar(20) not null default 'pending',
  requested_at timestamptz default now(),
  claimed_at timestamptz,
  adult_user_id integer references public.users(user_id) on delete set null
);
create index idx_legacy_review_token on public.legacy_parent_reviews(token_hash);
create index idx_legacy_review_status on public.legacy_parent_reviews(status);

create table public.ai_projects (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(user_id) on delete cascade,
  title varchar(255) not null,
  prompt text not null,
  generated_code text not null,
  project_type varchar(50) not null default 'website',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  public_id varchar(12) unique,
  is_public smallint not null default 0 check (is_public in (0, 1)),
  creator_name varchar(100),
  view_count integer not null default 0,
  like_count integer not null default 0,
  remix_count integer not null default 0
);
create index idx_ai_projects_user on public.ai_projects(user_id);

create table public.ai_project_likes (
  id integer generated by default as identity primary key,
  project_id integer not null references public.ai_projects(id) on delete cascade,
  user_id integer not null,
  created_at timestamptz default now(),
  constraint unique_like unique (project_id, user_id)
);

create table public.ai_project_versions (
  id integer generated by default as identity primary key,
  project_id integer not null references public.ai_projects(id) on delete cascade,
  version_num integer not null default 1,
  title varchar(255) not null default 'Untitled',
  generated_code text not null,
  prompt_history jsonb,
  label varchar(100) default 'Auto save',
  primary_color varchar(20) default '#FF7A00',
  accent_color varchar(20) default '#A855F7',
  created_at timestamptz default now()
);
create index idx_ai_project_versions_project on public.ai_project_versions(project_id);

create table public.ai_project_xp_awards (
  id integer generated by default as identity primary key,
  user_id integer not null,
  project_id integer not null,
  award_type varchar(20) not null,
  xp_earned integer not null,
  created_at timestamptz default now(),
  constraint uq_ai_project_xp_award unique (project_id, award_type)
);
create index idx_ai_project_xp_user on public.ai_project_xp_awards(user_id);

create table public.ai_usage_events (
  id bigint generated by default as identity primary key,
  operation varchar(32) not null,
  model varchar(80) not null,
  input_tokens integer not null default 0 check (input_tokens >= 0),
  output_tokens integer not null default 0 check (output_tokens >= 0),
  cache_creation_input_tokens integer not null default 0 check (cache_creation_input_tokens >= 0),
  cache_read_input_tokens integer not null default 0 check (cache_read_input_tokens >= 0),
  created_at timestamptz not null default now()
);
create index idx_ai_usage_created on public.ai_usage_events(created_at);
create index idx_ai_usage_operation on public.ai_usage_events(operation, created_at);

create table public.analytics_events (
  id bigint generated by default as identity primary key,
  event_name varchar(40) not null,
  user_id integer,
  journey_id char(36),
  campaign_code varchar(24),
  meta varchar(40),
  created_at timestamptz not null default now()
);
create index idx_analytics_event_created on public.analytics_events(event_name, created_at);
create index idx_analytics_user_event on public.analytics_events(user_id, event_name);
create index idx_analytics_journey_event on public.analytics_events(journey_id, event_name);
create index idx_analytics_campaign_event on public.analytics_events(campaign_code, event_name);

create table public.founding_family_leads (
  id bigint generated by default as identity primary key,
  email varchar(254) not null unique,
  user_id integer,
  source varchar(24) not null default 'pricing',
  consented_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_founding_family_joined on public.founding_family_leads(consented_at);

create table public.parent_notification_preferences (
  user_id integer primary key references public.users(user_id) on delete cascade,
  parent_email varchar(255) not null,
  verified_at timestamptz,
  verification_token_hash char(64),
  verification_expires_at timestamptz,
  unsubscribe_token_hash char(64) not null,
  notify_lessons smallint not null default 1 check (notify_lessons in (0, 1)),
  notify_exercises smallint not null default 1 check (notify_exercises in (0, 1)),
  notify_projects smallint not null default 1 check (notify_projects in (0, 1)),
  notify_publishing smallint not null default 1 check (notify_publishing in (0, 1)),
  enabled smallint not null default 1 check (enabled in (0, 1)),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index idx_parent_notification_email on public.parent_notification_preferences(parent_email);
create index idx_parent_verification_token on public.parent_notification_preferences(verification_token_hash);
create index idx_parent_unsubscribe_token on public.parent_notification_preferences(unsubscribe_token_hash);

create table public.student_milestones (
  id bigint generated by default as identity primary key,
  user_id integer not null references public.users(user_id) on delete cascade,
  event_type varchar(40) not null,
  event_key varchar(160) not null,
  title varchar(255) not null,
  detail varchar(500),
  target_url varchar(500),
  occurred_at timestamptz default now(),
  constraint uq_student_milestone unique (user_id, event_type, event_key)
);
create index idx_student_milestone_recent on public.student_milestones(user_id, occurred_at);

create table public.parent_notification_deliveries (
  id bigint generated by default as identity primary key,
  milestone_id bigint not null unique references public.student_milestones(id) on delete cascade,
  parent_email varchar(255) not null,
  status varchar(30) not null,
  provider_message_id varchar(255),
  error_code varchar(100),
  created_at timestamptz default now(),
  sent_at timestamptz
);

create table public.password_reset_tokens (
  id bigint generated by default as identity primary key,
  user_id integer not null references public.users(user_id) on delete cascade,
  token_hash char(64) not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz default now()
);
create index idx_password_reset_user_created on public.password_reset_tokens(user_id, created_at);
create index idx_password_reset_expiry on public.password_reset_tokens(expires_at);

create table public.rewards (
  id integer generated by default as identity primary key,
  student_id varchar(64) not null unique,
  name varchar(255) not null,
  xp_points integer not null default 0,
  updated_at timestamptz default now()
);
create index idx_rewards_xp on public.rewards(xp_points);

create table public.user_activity_daily (
  user_id integer not null,
  activity_date date not null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  login_count integer not null default 0 check (login_count >= 0),
  visit_count integer not null default 0 check (visit_count >= 0),
  primary key (user_id, activity_date)
);
create index idx_user_activity_date on public.user_activity_daily(activity_date);

create trigger set_student_game_score_updated_at before update on public.student_game_score
for each row execute function public.set_updated_at();
create trigger set_user_character_updated_at before update on public.user_character
for each row execute function public.set_updated_at();
create trigger set_adult_email_verifications_updated_at before update on public.adult_email_verifications
for each row execute function public.set_updated_at();
create trigger set_ai_projects_updated_at before update on public.ai_projects
for each row execute function public.set_updated_at();
create trigger set_founding_family_leads_updated_at before update on public.founding_family_leads
for each row execute function public.set_updated_at();
create trigger set_parent_notification_preferences_updated_at before update on public.parent_notification_preferences
for each row execute function public.set_updated_at();
create trigger set_rewards_updated_at before update on public.rewards
for each row execute function public.set_updated_at();

-- Data API access is denied by default. The trusted Vercel backend connects directly.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'users','students','lessons','puzzles','quiz_questions','student_lesson_progress',
    'student_puzzle_progress','student_quiz_attempt','parent_notification_log',
    'student_achievement','student_game_score','user_character','adult_email_verifications',
    'parent_child_links','legacy_parent_reviews','ai_projects','ai_project_likes',
    'ai_project_versions','ai_project_xp_awards','ai_usage_events','analytics_events',
    'founding_family_leads','parent_notification_preferences','student_milestones',
    'parent_notification_deliveries','password_reset_tokens','rewards','user_activity_daily'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
  end loop;
end;
$$;
