-- ── The optional grown-up email, kept where it belongs ───────────────────────
--
-- Run once from the Supabase SQL Editor.
--
-- WHY THIS IS NOT adult_email_verifications:
--
-- Two reasons, and the first is decisive. That table is
--   user_id INT NOT NULL PRIMARY KEY  REFERENCES Users(user_id)
-- so a row cannot exist without an account. An anonymous save has no account,
-- so the write is not merely unwise, it is impossible.
--
-- The second reason matters more. A row in adult_email_verifications means "the
-- adult who owns account N confirmed this address", and parent_child_links then
-- records consent_version, consented_at and public_sharing_allowed against it.
-- An address typed by whoever is at the keyboard means none of those things.
-- Writing it there would make every row in the consent record ambiguous, and
-- the consent record is the one table that has to stay unambiguous.
--
-- So this is what it honestly is: an adult asked for a copy of a link. Double
-- opt in, because an anonymous form that sends mail to any address a stranger
-- types is an abuse vector; nothing is sent beyond the single confirmation
-- until that confirmation is clicked. Unsubscribe token on every row.
--
-- THE UPGRADE PATH: if this person later creates a family account, consent is
-- recorded then, by the existing verified flow, in the existing table. This
-- table never becomes consent and never claims to be.

create table if not exists public.project_link_emails (
  id                 bigint generated by default as identity primary key,
  email              varchar(255) not null,
  -- Which unlisted project they asked for a copy of. Not a child identifier.
  project_public_id  varchar(24) not null,
  -- Nothing is sent past the first confirmation until this is set.
  confirmed_at       timestamptz,
  confirm_token_hash char(64),
  unsubscribe_token  char(64) not null,
  unsubscribed_at    timestamptz,
  created_at         timestamptz not null default now(),
  constraint uq_project_link_email unique (email, project_public_id)
);

create index if not exists idx_link_email_confirm on public.project_link_emails(confirm_token_hash);
create index if not exists idx_link_email_unsub   on public.project_link_emails(unsubscribe_token);

alter table public.project_link_emails enable row level security;
