-- XP for the steps inside a lesson.
--
-- Additive only: no existing table, column, row or index is touched, so this is
-- safe to run against the live database with learner progress in it. Nothing
-- already earned changes value, and nothing is recalculated.
--
-- Why this table exists: every lesson step already showed the child "+15 XP"
-- when they got it right, and that number went nowhere. It was not stored, not
-- added to any total, and not visible on the leaderboard — a reward that only
-- existed for as long as the message was on screen. Finishing the whole lesson
-- paid; the work inside it did not.
--
-- One row per (student, lesson, step). The unique constraint is what makes the
-- award safe to retry: re-running a step, refreshing the page, or a duplicated
-- request all collapse into the same row and pay once.

create table if not exists public.lesson_step_xp (
  id           bigint generated by default as identity primary key,
  user_id      integer not null references public.users(user_id) on delete cascade,
  lesson_id    integer not null,
  step_index   integer not null,
  xp_earned    integer not null default 0,
  completed_at timestamptz not null default now(),
  constraint uq_user_lesson_step unique (user_id, lesson_id, step_index)
);

create index if not exists idx_lesson_step_xp_user on public.lesson_step_xp(user_id);

-- Same posture as every other table: the public Data API is denied and the
-- trusted backend connects directly. A browser must never be able to write its
-- own XP rows.
alter table public.lesson_step_xp enable row level security;
