-- One row per learner per month the evidence email actually went out.
--
-- Additive only. The unique constraint is the idempotency: a twice-pressed
-- send button, a retried cron, or a duplicated request all collapse into one
-- send per family per calendar month.

create table if not exists public.monthly_digest_log (
  id       bigint generated by default as identity primary key,
  user_id  integer not null references public.users(user_id) on delete cascade,
  period   varchar(7) not null,
  status   varchar(20) not null default 'sent',
  sent_at  timestamptz not null default now(),
  constraint uq_digest_user_period unique (user_id, period)
);

alter table public.monthly_digest_log enable row level security;
